extern const GeoLayout engine_gate_geo[];
extern u8 engine_gate_darkgate_ci8[];
extern u8 engine_gate_darkgate_ci8_pal_rgba16[];
extern Vtx engine_gate_EndGate_mesh_layer_4_vtx_cull[8];
extern Vtx engine_gate_EndGate_mesh_layer_4_vtx_0[8];
extern Gfx engine_gate_EndGate_mesh_layer_4_tri_0[];
extern Gfx mat_engine_gate_Gate[];
extern Gfx mat_revert_engine_gate_Gate[];
extern Gfx engine_gate_EndGate_mesh_layer_4[];
extern Gfx engine_gate_material_revert_render_settings[];
