extern const GeoLayout sunblock_big_geo[];
extern Lights1 sunblock_big_Sunblock_002_lights;
extern u8 sunblock_big_sun_symbol2_ci4[];
extern u8 sunblock_big_sun_symbol2_ci4_pal_rgba16[];
extern Vtx sunblock_big_Sunblock_001_mesh_layer_5_vtx_cull[8];
extern Vtx sunblock_big_Sunblock_001_mesh_layer_5_vtx_0[24];
extern Gfx sunblock_big_Sunblock_001_mesh_layer_5_tri_0[];
extern Gfx mat_sunblock_big_Sunblock_002[];
extern Gfx mat_revert_sunblock_big_Sunblock_002[];
extern Gfx sunblock_big_Sunblock_001_mesh_layer_5[];
extern Gfx sunblock_big_material_revert_render_settings[];
