extern const GeoLayout boogoo_shyguy_000_switchcase_opt1[];
extern const GeoLayout boogoo_shyguy_geo[];
extern u8 boogoo_shyguy_BOOGOO1_i4[];
extern u8 boogoo_shyguy_BOOGOO2_i4[];
extern Vtx boogoo_shyguy_shyguy_mesh_layer_1_vtx_0[158];
extern Gfx boogoo_shyguy_shyguy_mesh_layer_1_tri_0[];
extern Gfx mat_boogoo_shyguy_BooGooObj_layer1[];
extern Gfx mat_revert_boogoo_shyguy_BooGooObj_layer1[];
extern Gfx boogoo_shyguy_shyguy_mesh_layer_1[];
extern Gfx boogoo_shyguy_material_revert_render_settings[];
