extern const GeoLayout unstable_rock_geo[];
extern Lights1 unstable_rock_SnowWall_001_layer1_lights;
extern u8 unstable_rock_snow_i8_i4[];
extern u8 unstable_rock_dirt_i8_i8[];
extern Vtx unstable_rock_Snow_002_mesh_layer_1_vtx_0[26];
extern Gfx unstable_rock_Snow_002_mesh_layer_1_tri_0[];
extern Gfx mat_unstable_rock_SnowWall_001_layer1[];
extern Gfx mat_revert_unstable_rock_SnowWall_001_layer1[];
extern Gfx unstable_rock_Snow_002_mesh_layer_1[];
extern Gfx unstable_rock_material_revert_render_settings[];
