extern const GeoLayout key_big_switch_opt1[];
extern const GeoLayout key_big_switch_opt2[];
extern const GeoLayout key_big_switch_opt3[];
extern const GeoLayout key_big_geo[];
extern Lights1 key_big_BigKey_lights;
extern u8 key_big_token_silver_i8[];
extern Vtx key_big_key_mesh_vtx_0[72];
extern Gfx key_big_key_mesh_tri_0[];
extern Vtx key_big_gem_mesh_vtx_0[15];
extern Gfx key_big_gem_mesh_tri_0[];
extern Gfx mat_key_big_BigKey[];
extern Gfx mat_key_big_Ruby[];
extern Gfx mat_revert_key_big_Ruby[];
extern Gfx mat_key_big_Emerald[];
extern Gfx mat_revert_key_big_Emerald[];
extern Gfx mat_key_big_Sapphire[];
extern Gfx mat_revert_key_big_Sapphire[];
extern Gfx mat_key_big_Diamond[];
extern Gfx mat_revert_key_big_Diamond[];
extern Gfx key_big_key_mesh[];
extern Gfx key_big_gem_mesh[];
extern Gfx key_big_gem_mesh_mat_override_Emerald_0[];
extern Gfx key_big_gem_mesh_mat_override_Sapphire_1[];
extern Gfx key_big_gem_mesh_mat_override_Diamond_2[];
extern Gfx key_big_material_revert_render_settings[];
