extern const GeoLayout light_button_Switch_opt1[];
extern const GeoLayout light_button_geo[];
extern u8 light_button_stoneplat_ci8[];
extern u8 light_button_stoneplat_ci8_pal_rgba16[];
extern Vtx light_button_Main_mesh_layer_1_vtx_0[48];
extern Gfx light_button_Main_mesh_layer_1_tri_0[];
extern Vtx light_button_Main_mesh_layer_1_vtx_1[6];
extern Gfx light_button_Main_mesh_layer_1_tri_1[];
extern Vtx light_button_Main_mesh_layer_1_vtx_2[20];
extern Gfx light_button_Main_mesh_layer_1_tri_2[];
extern Gfx mat_light_button_LightButton_001[];
extern Gfx mat_revert_light_button_LightButton_001[];
extern Gfx mat_light_button_Black_001[];
extern Gfx mat_light_button_Grey[];
extern Gfx mat_light_button_Yellow[];
extern Gfx light_button_Main_mesh_layer_1[];
extern Gfx light_button_Main_mesh_layer_1_mat_override_Yellow_0[];
extern Gfx light_button_material_revert_render_settings[];
