extern const GeoLayout paintbrush_geo[];
extern Lights1 paintbrush_poolcue_f3d_001_lights;
extern u8 paintbrush_ci4_pool_cue_ci4[];
extern u8 paintbrush_ci4_pool_cue_ci4_pal_rgba16[];
extern Vtx paintbrush_Brush_mesh_layer_1_vtx_cull[8];
extern Vtx paintbrush_Brush_mesh_layer_1_vtx_0[16];
extern Gfx paintbrush_Brush_mesh_layer_1_tri_0[];
extern Vtx paintbrush_Brush_mesh_layer_1_vtx_1[24];
extern Gfx paintbrush_Brush_mesh_layer_1_tri_1[];
extern Gfx mat_paintbrush_poolcue_f3d_001[];
extern Gfx mat_revert_paintbrush_poolcue_f3d_001[];
extern Gfx mat_paintbrush_BrushEnd[];
extern Gfx mat_revert_paintbrush_BrushEnd[];
extern Gfx paintbrush_Brush_mesh_layer_1[];
extern Gfx paintbrush_material_revert_render_settings[];
