extern const GeoLayout boogoo_koopa_root_ASpoonArma_001[];
extern const GeoLayout boogoo_koopa_root_AKnifeArma_002[];
extern const GeoLayout boogoo_koopa_AForkArma[];
extern const GeoLayout boogoo_koopa_root_BStaplerArma[];
extern const GeoLayout boogoo_koopa_root_BPenArma[];
extern const GeoLayout boogoo_koopa_BPhoneArma[];
extern const GeoLayout boogoo_koopa_CIcicleArma[];
extern const GeoLayout boogoo_koopa_root_DHammer[];
extern const GeoLayout boogoo_koopa_root_DPaddle[];
extern const GeoLayout boogoo_koopa_DCue[];
extern const GeoLayout boogoo_koopa_EPaintBrush[];
extern const GeoLayout boogoo_koopa_geo[];
extern Lights1 boogoo_koopa_Utencil_v4_001_lights;
extern Lights1 boogoo_koopa_Grey_v4_001_lights;
extern Lights1 boogoo_koopa_LightGrey_v4_001_lights;
extern Lights1 boogoo_koopa_poolcue_f3d_001_lights;
extern Lights1 boogoo_koopa_hammer_f3d_001_lights;
extern u8 boogoo_koopa_BOOGOO1_i4[];
extern u8 boogoo_koopa_BOOGOO2_i4[];
extern u8 boogoo_koopa_i8_utencil_i8[];
extern u8 boogoo_koopa_ci4_pyrojay_ice_ci4[];
extern u8 boogoo_koopa_ci4_pyrojay_ice_ci4_pal_rgba16[];
extern u8 boogoo_koopa_ci4_pool_cue_ci4[];
extern u8 boogoo_koopa_ci4_pool_cue_ci4_pal_rgba16[];
extern u8 boogoo_koopa_hammer_ci4[];
extern u8 boogoo_koopa_hammer_ci4_pal_rgba16[];
extern u8 boogoo_koopa_i8_pingpongpaddle_i8[];
extern u8 boogoo_koopa_darkhallwood_ci8[];
extern u8 boogoo_koopa_darkhallwood_ci8_pal_rgba16[];
extern Vtx boogoo_koopa_000_offset_001_mesh_layer_1_vtx_0[48];
extern Gfx boogoo_koopa_000_offset_001_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_000_offset_002_mesh_layer_1_vtx_0[117];
extern Gfx boogoo_koopa_000_offset_002_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_000_offset_003_mesh_layer_1_vtx_0[10];
extern Gfx boogoo_koopa_000_offset_003_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_000_offset_004_mesh_layer_1_vtx_0[41];
extern Gfx boogoo_koopa_000_offset_004_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_000_offset_005_mesh_layer_1_vtx_0[10];
extern Gfx boogoo_koopa_000_offset_005_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_000_offset_006_mesh_layer_1_vtx_0[41];
extern Gfx boogoo_koopa_000_offset_006_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_000_offset_007_mesh_layer_1_vtx_0[12];
extern Gfx boogoo_koopa_000_offset_007_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_000_offset_008_mesh_layer_1_vtx_0[31];
extern Gfx boogoo_koopa_000_offset_008_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_root_fork_mesh_layer_1_vtx_0[42];
extern Gfx boogoo_koopa_root_fork_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_root_root_spoon_mesh_layer_1_vtx_0[39];
extern Gfx boogoo_koopa_root_root_spoon_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_root_root_knife_mesh_layer_1_vtx_0[45];
extern Gfx boogoo_koopa_root_root_knife_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_root_phonedl_mesh_layer_1_vtx_0[60];
extern Gfx boogoo_koopa_root_phonedl_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_root_root_dl_mesh_layer_1_vtx_0[24];
extern Gfx boogoo_koopa_root_root_dl_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_root_root_dl_mesh_layer_1_vtx_1[24];
extern Gfx boogoo_koopa_root_root_dl_mesh_layer_1_tri_1[];
extern Vtx boogoo_koopa_root_root_pendl_mesh_layer_1_vtx_0[35];
extern Gfx boogoo_koopa_root_root_pendl_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_root_root_pendl_mesh_layer_1_vtx_1[15];
extern Gfx boogoo_koopa_root_root_pendl_mesh_layer_1_tri_1[];
extern Vtx boogoo_koopa_root_dl_mesh_layer_1_vtx_0[16];
extern Gfx boogoo_koopa_root_dl_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_root_cue_mesh_layer_1_vtx_0[16];
extern Gfx boogoo_koopa_root_cue_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_root_root_hammer_mesh_layer_1_vtx_0[82];
extern Gfx boogoo_koopa_root_root_hammer_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_root_root_paddle_mesh_layer_1_vtx_0[59];
extern Gfx boogoo_koopa_root_root_paddle_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_root_root_paddle_mesh_layer_1_vtx_1[32];
extern Gfx boogoo_koopa_root_root_paddle_mesh_layer_1_tri_1[];
extern Vtx boogoo_koopa_root_brush_mesh_layer_1_vtx_0[16];
extern Gfx boogoo_koopa_root_brush_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_root_brush_mesh_layer_1_vtx_1[24];
extern Gfx boogoo_koopa_root_brush_mesh_layer_1_tri_1[];
extern Vtx boogoo_koopa_000_offset_009_mesh_layer_1_vtx_0[10];
extern Gfx boogoo_koopa_000_offset_009_mesh_layer_1_tri_0[];
extern Vtx boogoo_koopa_000_offset_010_mesh_layer_1_vtx_0[30];
extern Gfx boogoo_koopa_000_offset_010_mesh_layer_1_tri_0[];
extern Gfx mat_boogoo_koopa_BooGooObj_layer1[];
extern Gfx mat_revert_boogoo_koopa_BooGooObj_layer1[];
extern Gfx mat_boogoo_koopa_Utencil_v4_001[];
extern Gfx mat_boogoo_koopa_Grey_v4_001[];
extern Gfx mat_boogoo_koopa_LightGrey_v4_001[];
extern Gfx mat_boogoo_koopa_Ice_v4_001[];
extern Gfx mat_revert_boogoo_koopa_Ice_v4_001[];
extern Gfx mat_boogoo_koopa_poolcue_f3d_001[];
extern Gfx mat_revert_boogoo_koopa_poolcue_f3d_001[];
extern Gfx mat_boogoo_koopa_hammer_f3d_001[];
extern Gfx mat_revert_boogoo_koopa_hammer_f3d_001[];
extern Gfx mat_boogoo_koopa_Paddle_001[];
extern Gfx mat_revert_boogoo_koopa_Paddle_001[];
extern Gfx mat_boogoo_koopa_TableWood_001[];
extern Gfx mat_revert_boogoo_koopa_TableWood_001[];
extern Gfx mat_boogoo_koopa_BrushEnd[];
extern Gfx mat_revert_boogoo_koopa_BrushEnd[];
extern Gfx boogoo_koopa_000_offset_001_mesh_layer_1[];
extern Gfx boogoo_koopa_000_offset_002_mesh_layer_1[];
extern Gfx boogoo_koopa_000_offset_003_mesh_layer_1[];
extern Gfx boogoo_koopa_000_offset_004_mesh_layer_1[];
extern Gfx boogoo_koopa_000_offset_005_mesh_layer_1[];
extern Gfx boogoo_koopa_000_offset_006_mesh_layer_1[];
extern Gfx boogoo_koopa_000_offset_007_mesh_layer_1[];
extern Gfx boogoo_koopa_000_offset_008_mesh_layer_1[];
extern Gfx boogoo_koopa_root_fork_mesh_layer_1[];
extern Gfx boogoo_koopa_root_root_spoon_mesh_layer_1[];
extern Gfx boogoo_koopa_root_root_knife_mesh_layer_1[];
extern Gfx boogoo_koopa_root_phonedl_mesh_layer_1[];
extern Gfx boogoo_koopa_root_root_dl_mesh_layer_1[];
extern Gfx boogoo_koopa_root_root_pendl_mesh_layer_1[];
extern Gfx boogoo_koopa_root_dl_mesh_layer_1[];
extern Gfx boogoo_koopa_root_cue_mesh_layer_1[];
extern Gfx boogoo_koopa_root_root_hammer_mesh_layer_1[];
extern Gfx boogoo_koopa_root_root_paddle_mesh_layer_1[];
extern Gfx boogoo_koopa_root_brush_mesh_layer_1[];
extern Gfx boogoo_koopa_000_offset_009_mesh_layer_1[];
extern Gfx boogoo_koopa_000_offset_010_mesh_layer_1[];
extern Gfx boogoo_koopa_material_revert_render_settings[];
