extern const GeoLayout block_piece_geo[];
extern const GeoLayout block_piece_shadow_geo[];
extern Lights1 block_piece_Jenga_002_lights;
extern u8 block_piece_living_wood2_ci8[];
extern u8 block_piece_living_wood2_ci8_pal_rgba16[];
extern Vtx block_piece_JengaPiece_mesh_layer_1_vtx_cull[8];
extern Vtx block_piece_JengaPiece_mesh_layer_1_vtx_0[20];
extern Gfx block_piece_JengaPiece_mesh_layer_1_tri_0[];
extern Gfx mat_block_piece_Jenga_002[];
extern Gfx mat_revert_block_piece_Jenga_002[];
extern Gfx block_piece_JengaPiece_mesh_layer_1[];
extern Gfx block_piece_material_revert_render_settings[];
