extern const GeoLayout pipeseg_geo[];
extern Lights1 pipeseg_PipeObj_001_lights;
extern u8 pipeseg_orangemetalbright_rgba32[];
extern Vtx pipeseg_PipeObject_mesh_layer_1_vtx_0[76];
extern Gfx pipeseg_PipeObject_mesh_layer_1_tri_0[];
extern Vtx pipeseg_PipeObject_mesh_layer_1_vtx_1[18];
extern Gfx pipeseg_PipeObject_mesh_layer_1_tri_1[];
extern Gfx mat_pipeseg_PipeObj_001[];
extern Gfx mat_pipeseg_Black_001[];
extern Gfx pipeseg_PipeObject_mesh_layer_1[];
extern Gfx pipeseg_material_revert_render_settings[];
