#include "src/game/envfx_snow.h"

const GeoLayout sl_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(6, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, sl_dl_201__Outside_geo),
			GEO_BRANCH(1, sl_dl_202__Main_Hall_geo),
			GEO_BRANCH(1, sl_dl_203__Hallway_geo),
			GEO_BRANCH(1, sl_dl_204__Living_Room_geo),
			GEO_BRANCH(1, sl_dl_205__Kitchen_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sl_dl_201__Outside_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sl_dl_Cobwebs_002_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Mansion_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Mansion_004_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -835, 3681, -9088, sl_dl_MountainExterior_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sl_dl_Tree_Leaves_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Trees_001_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sl_dl_202__Main_Hall_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Chandelier_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sl_dl_Chandelier_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_ConceptArtMainHall_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_MainHall_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_OpeningHallPlants_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sl_dl_OpeningHallPlants_003_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Painting_003_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -2900, 680, 6797, 0, 90, 0, sl_dl_StarPlaque_002_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -2900, 680, 6797, 0, 90, 0, sl_dl_StarPlaque_003_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sl_dl_203__Hallway_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Bookshelf_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Hallway_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_OpeningHallPlants_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sl_dl_OpeningHallPlants_002_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sl_dl_204__Living_Room_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Books_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, sl_dl_Carpet_001_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, sl_dl_CarpetEnd_001_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sl_dl_Cobwebs_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sl_dl_ConceptArtLivingRoom_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_ConceptArtLivingRoom_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Couch_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_FancyChair_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_LivingRoom_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_LTable_003_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sl_dl_205__Kitchen_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_chair_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, -65536, 0, 0, sl_dl_Cobwebs_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, sl_dl_ConceptArtKitchen_001_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Kitchen_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_KitchenGround_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sl_dl_KitchenGround_003_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_KitchenGround_006_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_KitchenGround_007_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Plate_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Stove_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Stove_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Stove_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Table_001_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sl_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_BELOW_CLOUDS, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 65536, 0, 0, 65536, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, sl_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, sl_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sl_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sl_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, sl_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
