#include "src/game/envfx_snow.h"

const GeoLayout security_cam_geo[] = {
	GEO_CULLING_RADIUS(4096),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, security_cam_tube_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, security_cam_cam_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -300, 87, 0, security_cam_cam_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, security_cam_cam_mesh_layer_5),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -345, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_generate_cam_beam),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, security_cam_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, security_cam_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
