extern const GeoLayout dice_enemy_switch_opt1[];
extern const GeoLayout dice_enemy_switch_opt2[];
extern const GeoLayout dice_enemy_switch_opt3[];
extern const GeoLayout dice_enemy_switch_opt4[];
extern const GeoLayout dice_enemy_switch_opt5[];
extern const GeoLayout dice_enemy_geo[];
extern Lights1 dice_enemy_Eye2_lights;
extern Lights1 dice_enemy_Eye3_lights;
extern Lights1 dice_enemy_Eye4_lights;
extern Lights1 dice_enemy_Eye5_lights;
extern Lights1 dice_enemy_Eye6_lights;
extern Lights1 dice_enemy_Dice_layer1_lights;
extern Lights1 dice_enemy_Eye1_lights;
extern u8 dice_enemy_dice_eye2_ia8[];
extern u8 dice_enemy_dice_eye3_ia8[];
extern u8 dice_enemy_dice_eye4_ia8[];
extern u8 dice_enemy_dice_eye5_ia8[];
extern u8 dice_enemy_dice_eye6_ia8[];
extern u8 dice_enemy_white_dice_faces_i4[];
extern u8 dice_enemy_dice_background_i8[];
extern u8 dice_enemy_dice_eye1_ia8[];
extern Vtx dice_enemy_legs_mesh_layer_1_vtx_0[16];
extern Gfx dice_enemy_legs_mesh_layer_1_tri_0[];
extern Vtx dice_enemy_dice_mesh_layer_1_vtx_0[24];
extern Gfx dice_enemy_dice_mesh_layer_1_tri_0[];
extern Vtx dice_enemy_eyes_mesh_layer_6_vtx_0[4];
extern Gfx dice_enemy_eyes_mesh_layer_6_tri_0[];
extern Gfx mat_dice_enemy_Black[];
extern Gfx mat_revert_dice_enemy_Black[];
extern Gfx mat_dice_enemy_Eye2[];
extern Gfx mat_revert_dice_enemy_Eye2[];
extern Gfx mat_dice_enemy_Eye3[];
extern Gfx mat_revert_dice_enemy_Eye3[];
extern Gfx mat_dice_enemy_Eye4[];
extern Gfx mat_revert_dice_enemy_Eye4[];
extern Gfx mat_dice_enemy_Eye5[];
extern Gfx mat_revert_dice_enemy_Eye5[];
extern Gfx mat_dice_enemy_Eye6[];
extern Gfx mat_revert_dice_enemy_Eye6[];
extern Gfx mat_dice_enemy_Dice_layer1[];
extern Gfx mat_revert_dice_enemy_Dice_layer1[];
extern Gfx mat_dice_enemy_Eye1[];
extern Gfx mat_revert_dice_enemy_Eye1[];
extern Gfx dice_enemy_legs_mesh_layer_1[];
extern Gfx dice_enemy_legs_mesh_layer_1_mat_override_Eye2_0[];
extern Gfx dice_enemy_legs_mesh_layer_1_mat_override_Eye3_1[];
extern Gfx dice_enemy_legs_mesh_layer_1_mat_override_Eye4_2[];
extern Gfx dice_enemy_legs_mesh_layer_1_mat_override_Eye5_3[];
extern Gfx dice_enemy_legs_mesh_layer_1_mat_override_Eye6_4[];
extern Gfx dice_enemy_dice_mesh_layer_1[];
extern Gfx dice_enemy_dice_mesh_layer_1_mat_override_Eye2_0[];
extern Gfx dice_enemy_dice_mesh_layer_1_mat_override_Eye3_1[];
extern Gfx dice_enemy_dice_mesh_layer_1_mat_override_Eye4_2[];
extern Gfx dice_enemy_dice_mesh_layer_1_mat_override_Eye5_3[];
extern Gfx dice_enemy_dice_mesh_layer_1_mat_override_Eye6_4[];
extern Gfx dice_enemy_eyes_mesh_layer_6[];
extern Gfx dice_enemy_eyes_mesh_layer_6_mat_override_Eye2_0[];
extern Gfx dice_enemy_eyes_mesh_layer_6_mat_override_Eye3_1[];
extern Gfx dice_enemy_eyes_mesh_layer_6_mat_override_Eye4_2[];
extern Gfx dice_enemy_eyes_mesh_layer_6_mat_override_Eye5_3[];
extern Gfx dice_enemy_eyes_mesh_layer_6_mat_override_Eye6_4[];
extern Gfx dice_enemy_material_revert_render_settings[];
