extern const GeoLayout end_shyguy_000_switchcase_opt1[];
extern const GeoLayout end_shyguy_geo[];
extern u8 end_shyguy_BOOGOO1_i4[];
extern u8 end_shyguy_BOOGOO2_i4[];
extern Vtx end_shyguy_shyguy_mesh_layer_1_vtx_0[158];
extern Gfx end_shyguy_shyguy_mesh_layer_1_tri_0[];
extern Gfx mat_end_shyguy_BooGooObj_layer1[];
extern Gfx mat_revert_end_shyguy_BooGooObj_layer1[];
extern Gfx mat_end_shyguy_BooGooObjTrans_layer1[];
extern Gfx mat_revert_end_shyguy_BooGooObjTrans_layer1[];
extern Gfx end_shyguy_shyguy_mesh_layer_1[];
extern Gfx end_shyguy_shyguy_mesh_layer_1_mat_override_BooGooObjTrans_0[];
extern Gfx end_shyguy_material_revert_render_settings[];
