extern const GeoLayout fan_blades_geo[];
extern Lights1 fan_blades_Fan_lights;
extern u8 fan_blades_MetalFence_ci4[];
extern u8 fan_blades_MetalFence_ci4_pal_rgba16[];
extern Vtx fan_blades_Fan_001_mesh_layer_1_vtx_cull[8];
extern Vtx fan_blades_Fan_001_mesh_layer_1_vtx_0[38];
extern Gfx fan_blades_Fan_001_mesh_layer_1_tri_0[];
extern Gfx mat_fan_blades_Fan[];
extern Gfx mat_revert_fan_blades_Fan[];
extern Gfx fan_blades_Fan_001_mesh_layer_1[];
extern Gfx fan_blades_material_revert_render_settings[];
