extern const GeoLayout c5_spinning_plat_geo[];
extern u8 c5_spinning_plat_deepplanks_redbrown_rgba16[];
extern u8 c5_spinning_plat_i4_matt_multitex_i4[];
extern Vtx c5_spinning_plat_splat_mesh_layer_1_vtx_0[61];
extern Gfx c5_spinning_plat_splat_mesh_layer_1_tri_0[];
extern Gfx rr_spinning_plat_tris1[];
extern Gfx rr_spinning_plat_tris2[];
extern Gfx mat_c5_spinning_plat_WoodFloorTrophyRoom_002_v5_002_layer1[];
extern Gfx mat_revert_c5_spinning_plat_WoodFloorTrophyRoom_002_v5_002_layer1[];
extern Gfx c5_spinning_plat_splat_mesh_layer_1[];
extern Gfx c5_spinning_plat_material_revert_render_settings[];
