extern const GeoLayout gravity_button_geo[];
extern u8 gravity_button_darkmetal_i8[];
extern Vtx gravity_button_button_mesh_layer_2_vtx_0[8];
extern Gfx gravity_button_button_mesh_layer_2_tri_0[];
extern Vtx gravity_button_button_mesh_layer_1_vtx_0[8];
extern Gfx gravity_button_button_mesh_layer_1_tri_0[];
extern Gfx mat_gravity_button_ButtonDecal[];
extern Gfx mat_revert_gravity_button_ButtonDecal[];
extern Gfx mat_gravity_button_Button[];
extern Gfx mat_revert_gravity_button_Button[];
extern Gfx gravity_button_button_mesh_layer_2[];
extern Gfx gravity_button_button_mesh_layer_1[];
extern Gfx gravity_button_material_revert_render_settings[];
