#include "src/game/envfx_snow.h"

const GeoLayout sl_area_3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(3, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, sl_dl_301__Outside_geo),
			GEO_BRANCH(1, sl_dl_302__Main_Hall_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sl_dl_301__Outside_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sl_dl_Cobwebs_005_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Mansion_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sl_dl_Mansion_005_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Mansion_006_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -835, 3681, -9088, sl_dl_MountainExterior_002_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sl_dl_302__Main_Hall_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sl_dl_Cobwebs_003_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_Light_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_MainHall_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_StarPlaque_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_StarPlaque_005_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sl_area_3[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_BELOW_CLOUDS, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 131072, 0, 0, 131072, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, sl_area_3_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sl_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sl_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
