extern const GeoLayout boogoo_goomba_geo[];
extern u8 boogoo_goomba_BOOGOO1_i4[];
extern u8 boogoo_goomba_BOOGOO2_i4[];
extern Vtx boogoo_goomba_000_displaylist_mesh_layer_1_vtx_0[4];
extern Gfx boogoo_goomba_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx boogoo_goomba_000_offset_002_mesh_layer_1_vtx_0[57];
extern Gfx boogoo_goomba_000_offset_002_mesh_layer_1_tri_0[];
extern Vtx boogoo_goomba_000_offset_003_mesh_layer_1_vtx_0[28];
extern Gfx boogoo_goomba_000_offset_003_mesh_layer_1_tri_0[];
extern Vtx boogoo_goomba_000_offset_004_mesh_layer_1_vtx_0[28];
extern Gfx boogoo_goomba_000_offset_004_mesh_layer_1_tri_0[];
extern Gfx mat_boogoo_goomba_BooGooObj_layer1[];
extern Gfx mat_revert_boogoo_goomba_BooGooObj_layer1[];
extern Gfx boogoo_goomba_000_displaylist_mesh_layer_1[];
extern Gfx boogoo_goomba_000_offset_002_mesh_layer_1[];
extern Gfx boogoo_goomba_000_offset_003_mesh_layer_1[];
extern Gfx boogoo_goomba_000_offset_004_mesh_layer_1[];
extern Gfx boogoo_goomba_material_revert_render_settings[];
