extern const GeoLayout red_button_geo[];
extern Lights1 red_button_RedButton_002_lights;
extern Lights1 red_button_ButtonDecal_002_lights;
extern Vtx red_button_RedButton_mesh_layer_1_vtx_0[12];
extern Gfx red_button_RedButton_mesh_layer_1_tri_0[];
extern Vtx red_button_RedButton_mesh_layer_2_vtx_0[10];
extern Gfx red_button_RedButton_mesh_layer_2_tri_0[];
extern Gfx mat_red_button_RedButton_002[];
extern Gfx mat_revert_red_button_RedButton_002[];
extern Gfx mat_red_button_ButtonDecal_002[];
extern Gfx mat_revert_red_button_ButtonDecal_002[];
extern Gfx red_button_RedButton_mesh_layer_1[];
extern Gfx red_button_RedButton_mesh_layer_2[];
extern Gfx red_button_material_revert_render_settings[];
