extern const GeoLayout shyguy_group_switch_opt1[];
extern const GeoLayout shyguy_group_geo[];
extern Lights1 shyguy_group_Shyguy1_002_lights;
extern Lights1 shyguy_group_Shyguy2_002_lights;
extern u8 shyguy_group_shyguy1_black_i8[];
extern u8 shyguy_group_shyguy2_ci8[];
extern u8 shyguy_group_shyguy2_ci8_pal_rgba16[];
extern Vtx shyguy_group_group_mesh_layer_1_vtx_0[48];
extern Gfx shyguy_group_group_mesh_layer_1_tri_0[];
extern Vtx shyguy_group_group_mesh_layer_1_vtx_1[323];
extern Gfx shyguy_group_group_mesh_layer_1_tri_1[];
extern Vtx shyguy_group_group_mesh_layer_1_vtx_2[269];
extern Gfx shyguy_group_group_mesh_layer_1_tri_2[];
extern Gfx mat_shyguy_group_Shyguy1_002[];
extern Gfx mat_shyguy_group_Shyguy2_002[];
extern Gfx mat_revert_shyguy_group_Shyguy2_002[];
extern Gfx mat_shyguy_group_Black[];
extern Gfx shyguy_group_group_mesh_layer_1[];
extern Gfx shyguy_group_material_revert_render_settings[];
