#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/ssl/header.h"

#include "levels/ssl/areas/1/5/geo.inc.c"
#include "levels/ssl/areas/2/4/geo.inc.c"
#include "levels/ssl/pyramid_top/geo.inc.c"
#include "levels/ssl/tox_box/geo.inc.c"
#include "levels/ssl/areas/1/geo.inc.c"
#include "levels/ssl/grindel/geo.inc.c"
#include "levels/ssl/spindel/geo.inc.c"
#include "levels/ssl/moving_pyramid_wall/geo.inc.c"
#include "levels/ssl/pyramid_elevator/geo.inc.c"
#include "levels/ssl/eyerok_col/geo.inc.c"
#include "levels/ssl/areas/2/geo.inc.c"
#include "levels/ssl/areas/3/geo.inc.c"

#include "levels/ssl/geo.inc.c"

#include "levels/ssl/painting_enemy/geo.inc.c"
#include "levels/ssl/boogoo_goomba/geo.inc.c"
#include "levels/ssl/boogoo_koopa/geo.inc.c"
#include "levels/ssl/boogoo_shyguy/geo.inc.c"
#include "levels/ssl/paintbrush/geo.inc.c"
#include "levels/ssl/painting_brick/geo.inc.c"
#include "levels/ssl/cage_goo/geo.inc.c"
#include "levels/ssl/ag_boogoo/geo.inc.c"
#include "levels/ssl/bg_asteroid/geo.inc.c"
#include "levels/ssl/o2_boogoo/geo.inc.c"
#include "levels/ssl/spinning_plat/geo.inc.c"
#include "levels/ssl/big_spinning_plat/geo.inc.c"
#include "levels/ssl/antenna_ball/geo.inc.c"