extern const GeoLayout ssl_area_1_geo[];
extern const GeoLayout ssl_dl_101__Opening_geo[];
extern const GeoLayout ssl_area_1[];
extern const Collision ssl_area_1_collision[];
extern const u8 ssl_area_1_collision_rooms[];
extern const MacroObject ssl_area_1_macro_objs[];
extern u8 ssl_dl_gold_rock_ground_edge_rgba16[];
extern u8 ssl_dl__32x_multigrass_i8_lowcontrast_SUPAbright_i8[];
extern u8 ssl_dl_gold_rock_ground2_bright_rgba16[];
extern Vtx ssl_dl_OpeningGround_mesh_layer_1_vtx_cull[8];
extern Vtx ssl_dl_OpeningGround_mesh_layer_1_vtx_0[24];
extern Gfx ssl_dl_OpeningGround_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_OpeningGround_mesh_layer_1_vtx_1[8];
extern Gfx ssl_dl_OpeningGround_mesh_layer_1_tri_1[];
extern Gfx mat_ssl_dl_GroundEdge_layer1[];
extern Gfx mat_revert_ssl_dl_GroundEdge_layer1[];
extern Gfx mat_ssl_dl_OutsideGround_layer1[];
extern Gfx mat_revert_ssl_dl_OutsideGround_layer1[];
extern Gfx ssl_dl_OpeningGround_mesh_layer_1[];
extern Gfx ssl_dl_material_revert_render_settings[];
