#include <PR/ultratypes.h>
#include <PR/gbi.h>

#include "dialog_ids.h"
#include "level_misc_macros.h"
#include "macros.h"
#include "macro_preset_names.h"
#include "moving_texture_macros.h"
#include "special_preset_names.h"
#include "surface_terrains.h"
#include "textures.h"
#include "types.h"

#include "make_const_nonconst.h"
// LEVEL DATA
#include "levels/ssl/texture.inc.c"
// This is an oddity, but it is assumed this because of the likelyhood SSL's
// course used to be smaller in a prototype build and that moving areas around
// caused this discrepency. (See the 3 Star Course theory)
#include "levels/ssl/areas/2/4/model.inc.c"
#include "levels/ssl/areas/1/1/model.inc.c"
#include "levels/ssl/areas/1/2/model.inc.c"
#include "levels/ssl/areas/1/3/model.inc.c"
#include "levels/ssl/areas/1/4/model.inc.c"
#include "levels/ssl/pyramid_top/model.inc.c"
#include "levels/ssl/tox_box/model.inc.c"
#include "levels/ssl/areas/1/collision.inc.c"
#include "levels/ssl/areas/1/macro.inc.c"
#include "levels/ssl/pyramid_top/collision.inc.c"
#include "levels/ssl/tox_box/collision.inc.c"
#include "levels/ssl/areas/1/movtext.inc.c"
#include "levels/ssl/areas/2/1/model.inc.c"
#include "levels/ssl/areas/2/2/model.inc.c"
#include "levels/ssl/areas/2/3/model.inc.c"
#include "levels/ssl/areas/3/1/model.inc.c"
#include "levels/ssl/areas/3/2/model.inc.c"
#include "levels/ssl/grindel/model.inc.c"
#include "levels/ssl/spindel/model.inc.c"
#include "levels/ssl/moving_pyramid_wall/model.inc.c"
#include "levels/ssl/pyramid_elevator/model.inc.c"
#include "levels/ssl/eyerok_col/model.inc.c" // Blank file
#include "levels/ssl/areas/2/collision.inc.c"
#include "levels/ssl/areas/3/collision.inc.c"
#include "levels/ssl/areas/2/macro.inc.c"
#include "levels/ssl/areas/3/macro.inc.c"
#include "levels/ssl/grindel/collision.inc.c"
#include "levels/ssl/spindel/collision.inc.c"
#include "levels/ssl/moving_pyramid_wall/collision.inc.c"
#include "levels/ssl/pyramid_elevator/collision.inc.c"
#include "levels/ssl/eyerok_col/collision.inc.c"
#include "levels/ssl/areas/2/movtext.inc.c"

#include "levels/ssl/leveldata.inc.c"

#include "levels/ssl/painting_enemy/model.inc.c"
#include "levels/ssl/painting_enemy/collision.inc.c"
#include "levels/ssl/boogoo_goomba/model.inc.c"
#include "levels/ssl/boogoo_koopa/model.inc.c"
#include "levels/ssl/boogoo_shyguy/model.inc.c"
#include "levels/ssl/paintbrush/model.inc.c"
#include "levels/ssl/painting_brick/model.inc.c"
#include "levels/ssl/painting_brick/collision.inc.c"
#include "levels/ssl/cage_goo/model.inc.c"
#include "levels/ssl/ag_boogoo/collision.inc.c"
#include "levels/ssl/ag_boogoo/model.inc.c"
#include "levels/ssl/bg_asteroid/model.inc.c"
#include "levels/ssl/bg_asteroid/collision.inc.c"
#include "levels/ssl/o2_boogoo/model.inc.c"
#include "levels/ssl/o2_boogoo/collision.inc.c"
#include "levels/ssl/spinning_plat/model.inc.c"
#include "levels/ssl/spinning_plat/collision.inc.c"
#include "levels/ssl/big_spinning_plat/model.inc.c"
#include "levels/ssl/big_spinning_plat/collision.inc.c"
#include "levels/ssl/antenna_ball/model.inc.c"
#include "levels/ssl/suncube/model.inc.c"