#include "levels/ssl/area_1/collision.inc.c"
#include "levels/ssl/area_1/room.inc.c"
#include "levels/ssl/area_1/macro.inc.c"
#include "levels/ssl/area_1/spline.inc.c"
#include "levels/ssl/model.inc.c"
