extern const GeoLayout blue_cushion_geo[];
extern Lights1 blue_cushion_Couch_lights;
extern u8 blue_cushion_cushions_blue_ci8[];
extern u8 blue_cushion_cushions_blue_ci8_pal_rgba16[];
extern Vtx blue_cushion_BlueCushion_mesh_layer_1_vtx_0[16];
extern Gfx blue_cushion_BlueCushion_mesh_layer_1_tri_0[];
extern Gfx mat_blue_cushion_Couch[];
extern Gfx mat_revert_blue_cushion_Couch[];
extern Gfx blue_cushion_BlueCushion_mesh_layer_1[];
extern Gfx blue_cushion_material_revert_render_settings[];
