extern const GeoLayout c2_lightning_strike_switch_opt1[];
extern const GeoLayout c2_lightning_strike_geo[];
extern u8 c2_lightning_strike_i8_circle2_i8[];
extern u8 c2_lightning_strike_dot_i8[];
extern u8 c2_lightning_strike_amp_electricity_ci4[];
extern u8 c2_lightning_strike_amp_electricity_ci4_pal_rgba16[];
extern Vtx c2_lightning_strike_mark_mesh_layer_5_vtx_0[4];
extern Gfx c2_lightning_strike_mark_mesh_layer_5_tri_0[];
extern Vtx c2_lightning_strike_lightning_mesh_layer_1_vtx_0[61];
extern Gfx c2_lightning_strike_lightning_mesh_layer_1_tri_0[];
extern Vtx c2_lightning_strike_lightning_mesh_layer_4_vtx_0[24];
extern Gfx c2_lightning_strike_lightning_mesh_layer_4_tri_0[];
extern Gfx mat_c2_lightning_strike_Indicator_layer5[];
extern Gfx mat_revert_c2_lightning_strike_Indicator_layer5[];
extern Gfx mat_c2_lightning_strike_Lighting_001[];
extern Gfx mat_revert_c2_lightning_strike_Lighting_001[];
extern Gfx mat_c2_lightning_strike_Electric[];
extern Gfx mat_revert_c2_lightning_strike_Electric[];
extern Gfx mat_c2_lightning_strike_Blank[];
extern Gfx c2_lightning_strike_mark_mesh_layer_5[];
extern Gfx c2_lightning_strike_lightning_mesh_layer_1[];
extern Gfx c2_lightning_strike_lightning_mesh_layer_1_mat_override_Blank_0[];
extern Gfx c2_lightning_strike_lightning_mesh_layer_4[];
extern Gfx c2_lightning_strike_lightning_mesh_layer_4_mat_override_Blank_0[];
extern Gfx c2_lightning_strike_material_revert_render_settings[];
