extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_dl_101__City_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const u8 ccm_area_1_collision_rooms[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_Brick_lights;
extern Lights1 ccm_dl_Edge_lights;
extern Lights1 ccm_dl_House_layer1_lights;
extern Lights1 ccm_dl_Lego_lights;
extern Lights1 ccm_dl_LegoWall_lights;
extern u8 ccm_dl_i8_brick_floor_i8[];
extern u8 ccm_dl_i8_rough_wall_i8[];
extern u8 ccm_dl_i8_lego_mirror_i4[];
extern u8 ccm_dl_window_multitex_rgba16[];
extern u8 ccm_dl_i8_lego_mirror_i8[];
extern u8 ccm_dl_mirror_lego_wall_rgba16[];
extern Vtx ccm_dl_City_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_City_mesh_layer_1_vtx_0[4];
extern Gfx ccm_dl_City_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_City_mesh_layer_1_vtx_1[10];
extern Gfx ccm_dl_City_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_House_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_House_mesh_layer_1_vtx_0[10];
extern Gfx ccm_dl_House_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_House_mesh_layer_1_vtx_1[4];
extern Gfx ccm_dl_House_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Lego_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Lego_mesh_layer_1_vtx_0[16];
extern Gfx ccm_dl_Lego_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Lego_mesh_layer_1_vtx_1[4];
extern Gfx ccm_dl_Lego_mesh_layer_1_tri_1[];
extern Gfx mat_ccm_dl_Brick[];
extern Gfx mat_revert_ccm_dl_Brick[];
extern Gfx mat_ccm_dl_Edge[];
extern Gfx mat_revert_ccm_dl_Edge[];
extern Gfx mat_ccm_dl_House_layer1[];
extern Gfx mat_revert_ccm_dl_House_layer1[];
extern Gfx mat_ccm_dl_Lego[];
extern Gfx mat_revert_ccm_dl_Lego[];
extern Gfx mat_ccm_dl_LegoWall[];
extern Gfx mat_revert_ccm_dl_LegoWall[];
extern Gfx ccm_dl_City_mesh_layer_1[];
extern Gfx ccm_dl_House_mesh_layer_1[];
extern Gfx ccm_dl_Lego_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
