extern const GeoLayout fake_dirt_wall_geo[];
extern Lights1 fake_dirt_wall_DirtWall_001_lights;
extern u8 fake_dirt_wall_dirtwall_ci8[];
extern u8 fake_dirt_wall_dirtwall_ci8_pal_rgba16[];
extern Vtx fake_dirt_wall_Grass_003_mesh_layer_1_vtx_0[4];
extern Gfx fake_dirt_wall_Grass_003_mesh_layer_1_tri_0[];
extern Gfx mat_fake_dirt_wall_DirtWall_001[];
extern Gfx mat_revert_fake_dirt_wall_DirtWall_001[];
extern Gfx fake_dirt_wall_Grass_003_mesh_layer_1[];
extern Gfx fake_dirt_wall_material_revert_render_settings[];
