extern const GeoLayout boom_boom_2d_switch_opt1[];
extern const GeoLayout boom_boom_2d_switch_opt2[];
extern const GeoLayout boom_boom_2d_switch_opt3[];
extern const GeoLayout boom_boom_2d_switch_opt4[];
extern const GeoLayout boom_boom_2d_geo[];
extern u8 boom_boom_2d_boomboom_1_ci4[];
extern u8 boom_boom_2d_boomboom_1_ci4_pal_rgba16[];
extern u8 boom_boom_2d_boomboom_2_ci4[];
extern u8 boom_boom_2d_boomboom_2_ci4_pal_rgba16[];
extern u8 boom_boom_2d_boomboom_3_ci4[];
extern u8 boom_boom_2d_boomboom_3_ci4_pal_rgba16[];
extern u8 boom_boom_2d_boomboom_4_ci4[];
extern u8 boom_boom_2d_boomboom_4_ci4_pal_rgba16[];
extern Vtx boom_boom_2d_boomboom_mesh_layer_4_vtx_0[4];
extern Gfx boom_boom_2d_boomboom_mesh_layer_4_tri_0[];
extern Gfx mat_boom_boom_2d_BoomBoom[];
extern Gfx mat_revert_boom_boom_2d_BoomBoom[];
extern Gfx mat_boom_boom_2d_BoomBoom1[];
extern Gfx mat_revert_boom_boom_2d_BoomBoom1[];
extern Gfx mat_boom_boom_2d_BoomBoom2[];
extern Gfx mat_revert_boom_boom_2d_BoomBoom2[];
extern Gfx mat_boom_boom_2d_BoomBoom3[];
extern Gfx mat_revert_boom_boom_2d_BoomBoom3[];
extern Gfx mat_boom_boom_2d_BoomBoom4[];
extern Gfx mat_revert_boom_boom_2d_BoomBoom4[];
extern Gfx boom_boom_2d_boomboom_mesh_layer_4[];
extern Gfx boom_boom_2d_boomboom_mesh_layer_4_mat_override_BoomBoom1_0[];
extern Gfx boom_boom_2d_boomboom_mesh_layer_4_mat_override_BoomBoom2_1[];
extern Gfx boom_boom_2d_boomboom_mesh_layer_4_mat_override_BoomBoom3_2[];
extern Gfx boom_boom_2d_boomboom_mesh_layer_4_mat_override_BoomBoom4_3[];
extern Gfx boom_boom_2d_material_revert_render_settings[];
