extern const GeoLayout gold_medal_switch_opt1[];
extern const GeoLayout gold_medal_geo[];
extern u8 gold_medal_Medal3_ia8[];
extern Vtx gold_medal_medal_mesh_layer_1_vtx_0[25];
extern Gfx gold_medal_medal_mesh_layer_1_tri_0[];
extern Gfx mat_gold_medal_Medal2_v4_001[];
extern Gfx mat_revert_gold_medal_Medal2_v4_001[];
extern Gfx mat_gold_medal_MedalRed[];
extern Gfx mat_revert_gold_medal_MedalRed[];
extern Gfx gold_medal_medal_mesh_layer_1[];
extern Gfx gold_medal_medal_mesh_layer_1_mat_override_MedalRed_0[];
extern Gfx gold_medal_material_revert_render_settings[];
