extern const GeoLayout sl_area_1_geo[];
extern const GeoLayout sl_dl_101__Outside_geo[];
extern const GeoLayout sl_dl_102__Main_Hall_geo[];
extern const GeoLayout sl_dl_103__Hallway_geo[];
extern const GeoLayout sl_dl_104__Living_Room_geo[];
extern const GeoLayout sl_dl_105__Kitchen_geo[];
extern const GeoLayout sl_dl_106__Lounge_geo[];
extern const GeoLayout sl_dl_107__Entertainment_Room_geo[];
extern const GeoLayout sl_dl_108__Basement_geo[];
extern const GeoLayout sl_dl_109__Bedroom_geo[];
extern const GeoLayout sl_area_1[];
extern const Collision sl_area_1_collision[];
extern const u8 sl_area_1_collision_rooms[];
extern const MacroObject sl_area_1_macro_objs[];
extern Lights1 sl_dl_MainHallFloor_lights;
extern Vtx sl_dl_MainHall_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_MainHall_mesh_layer_1_vtx_0[88];
extern Gfx sl_dl_MainHall_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Hallway_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Hallway_mesh_layer_1_vtx_0[253];
extern Gfx sl_dl_Hallway_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Hallway_001_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Hallway_001_mesh_layer_1_vtx_0[1002];
extern Gfx sl_dl_Hallway_001_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Hallway_002_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Hallway_002_mesh_layer_1_vtx_0[1017];
extern Gfx sl_dl_Hallway_002_mesh_layer_1_tri_0[];
extern Vtx sl_dl_LivingRoom_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_LivingRoom_mesh_layer_1_vtx_0[68];
extern Gfx sl_dl_LivingRoom_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Kitchen_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Kitchen_mesh_layer_1_vtx_0[70];
extern Gfx sl_dl_Kitchen_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Lounge_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Lounge_mesh_layer_1_vtx_0[68];
extern Gfx sl_dl_Lounge_mesh_layer_1_tri_0[];
extern Vtx sl_dl_EntertainmentRoom_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_EntertainmentRoom_mesh_layer_1_vtx_0[62];
extern Gfx sl_dl_EntertainmentRoom_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Basement_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Basement_mesh_layer_1_vtx_0[67];
extern Gfx sl_dl_Basement_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Bedroom_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Bedroom_mesh_layer_1_vtx_0[66];
extern Gfx sl_dl_Bedroom_mesh_layer_1_tri_0[];
extern Gfx mat_sl_dl_MainHallFloor[];
extern Gfx sl_dl_MainHall_mesh_layer_1[];
extern Gfx sl_dl_Hallway_mesh_layer_1[];
extern Gfx sl_dl_Hallway_001_mesh_layer_1[];
extern Gfx sl_dl_Hallway_002_mesh_layer_1[];
extern Gfx sl_dl_LivingRoom_mesh_layer_1[];
extern Gfx sl_dl_Kitchen_mesh_layer_1[];
extern Gfx sl_dl_Lounge_mesh_layer_1[];
extern Gfx sl_dl_EntertainmentRoom_mesh_layer_1[];
extern Gfx sl_dl_Basement_mesh_layer_1[];
extern Gfx sl_dl_Bedroom_mesh_layer_1[];
extern Gfx sl_dl_material_revert_render_settings[];
