extern const GeoLayout sl_area_1_geo[];
extern const GeoLayout sl_dl_101__Outside_geo[];
extern const GeoLayout sl_dl_102__Main_Hall_geo[];
extern const GeoLayout sl_dl_103__Hallway_geo[];
extern const GeoLayout sl_dl_104__Living_Room_geo[];
extern const GeoLayout sl_dl_105__Kitchen_geo[];
extern const GeoLayout sl_dl_106__Lounge_geo[];
extern const GeoLayout sl_dl_107__Entertainment_Room_geo[];
extern const GeoLayout sl_dl_108__Basement_geo[];
extern const GeoLayout sl_dl_109__Bedroom_geo[];
extern const GeoLayout sl_area_1[];
extern const Collision sl_area_1_collision[];
extern const u8 sl_area_1_collision_rooms[];
extern const MacroObject sl_area_1_macro_objs[];
extern u8 sl_dl_stonepanels_i8_i8[];
extern u8 sl_dl_fancy_wall_ci8[];
extern u8 sl_dl_fancy_wall_ci8_pal_rgba16[];
extern u8 sl_dl_shortbluewall_rgba16[];
extern u8 sl_dl_deepplanks_mixed2_rgba16[];
extern u8 sl_dl_i4_matt_multitex_i4[];
extern u8 sl_dl_fancy_wall_cropped_ci8[];
extern u8 sl_dl_fancy_wall_cropped_ci8_pal_rgba16[];
extern u8 sl_dl_living_wood2_ci8[];
extern u8 sl_dl_living_wood2_ci8_pal_rgba16[];
extern u8 sl_dl_kitchenwall2_ci8[];
extern u8 sl_dl_kitchenwall2_ci8_pal_rgba16[];
extern u8 sl_dl_marbletiles_i8[];
extern u8 sl_dl_loungewall_ci8[];
extern u8 sl_dl_loungewall_ci8_pal_rgba16[];
extern u8 sl_dl_loungecarpet_i8[];
extern u8 sl_dl_gray_woodpillar_i8[];
extern u8 sl_dl_gameroomwall_ci8[];
extern u8 sl_dl_gameroomwall_ci8_pal_rgba16[];
extern u8 sl_dl_ci4_green_carpet_ci4[];
extern u8 sl_dl_ci4_green_carpet_ci4_pal_rgba16[];
extern u8 sl_dl_carpet_end_green_ci8[];
extern u8 sl_dl_carpet_end_green_ci8_pal_rgba16[];
extern u8 sl_dl_i8_garage_wall_i8[];
extern u8 sl_dl_garage_floor2_i8[];
extern u8 sl_dl_i8_flowerwall_i8[];
extern u8 sl_dl_purple_carpet_ci4[];
extern u8 sl_dl_purple_carpet_ci4_pal_rgba16[];
extern Vtx sl_dl_MainHall_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_MainHall_mesh_layer_1_vtx_0[16];
extern Gfx sl_dl_MainHall_mesh_layer_1_tri_0[];
extern Vtx sl_dl_MainHall_mesh_layer_1_vtx_1[52];
extern Gfx sl_dl_MainHall_mesh_layer_1_tri_1[];
extern Vtx sl_dl_Hallway_002_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Hallway_002_mesh_layer_1_vtx_0[1519];
extern Gfx sl_dl_Hallway_002_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Hallway_002_mesh_layer_1_vtx_1[490];
extern Gfx sl_dl_Hallway_002_mesh_layer_1_tri_1[];
extern Vtx sl_dl_LivingRoom_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_LivingRoom_mesh_layer_1_vtx_0[42];
extern Gfx sl_dl_LivingRoom_mesh_layer_1_tri_0[];
extern Vtx sl_dl_LivingRoom_mesh_layer_1_vtx_1[10];
extern Gfx sl_dl_LivingRoom_mesh_layer_1_tri_1[];
extern Vtx sl_dl_Kitchen_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Kitchen_mesh_layer_1_vtx_0[37];
extern Gfx sl_dl_Kitchen_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Kitchen_mesh_layer_1_vtx_1[10];
extern Gfx sl_dl_Kitchen_mesh_layer_1_tri_1[];
extern Vtx sl_dl_Lounge_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Lounge_mesh_layer_1_vtx_0[45];
extern Gfx sl_dl_Lounge_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Lounge_mesh_layer_1_vtx_1[10];
extern Gfx sl_dl_Lounge_mesh_layer_1_tri_1[];
extern Vtx sl_dl_Lounge_mesh_layer_1_vtx_2[56];
extern Gfx sl_dl_Lounge_mesh_layer_1_tri_2[];
extern Vtx sl_dl_EntertainmentRoom_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_EntertainmentRoom_mesh_layer_1_vtx_0[37];
extern Gfx sl_dl_EntertainmentRoom_mesh_layer_1_tri_0[];
extern Vtx sl_dl_EntertainmentRoom_mesh_layer_1_vtx_1[10];
extern Gfx sl_dl_EntertainmentRoom_mesh_layer_1_tri_1[];
extern Vtx sl_dl_EntertainmentRoom_mesh_layer_2_vtx_cull[8];
extern Vtx sl_dl_EntertainmentRoom_mesh_layer_2_vtx_0[4];
extern Gfx sl_dl_EntertainmentRoom_mesh_layer_2_tri_0[];
extern Vtx sl_dl_EntertainmentRoom_mesh_layer_2_vtx_1[16];
extern Gfx sl_dl_EntertainmentRoom_mesh_layer_2_tri_1[];
extern Vtx sl_dl_Basement_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Basement_mesh_layer_1_vtx_0[44];
extern Gfx sl_dl_Basement_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Basement_mesh_layer_1_vtx_1[10];
extern Gfx sl_dl_Basement_mesh_layer_1_tri_1[];
extern Vtx sl_dl_Bedroom_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Bedroom_mesh_layer_1_vtx_0[32];
extern Gfx sl_dl_Bedroom_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Bedroom_mesh_layer_1_vtx_1[10];
extern Gfx sl_dl_Bedroom_mesh_layer_1_tri_1[];
extern Gfx mat_sl_dl_MainHallFloor[];
extern Gfx mat_revert_sl_dl_MainHallFloor[];
extern Gfx mat_sl_dl_MainHallWall[];
extern Gfx mat_revert_sl_dl_MainHallWall[];
extern Gfx mat_sl_dl_Wall_002[];
extern Gfx mat_revert_sl_dl_Wall_002[];
extern Gfx mat_sl_dl_WoodFloor_002_layer1[];
extern Gfx mat_revert_sl_dl_WoodFloor_002_layer1[];
extern Gfx mat_sl_dl_LivWall_v4_001[];
extern Gfx mat_revert_sl_dl_LivWall_v4_001[];
extern Gfx mat_sl_dl_LivFloor_v4_001[];
extern Gfx mat_revert_sl_dl_LivFloor_v4_001[];
extern Gfx mat_sl_dl_KitchenWall[];
extern Gfx mat_revert_sl_dl_KitchenWall[];
extern Gfx mat_sl_dl_KitchenFloor[];
extern Gfx mat_revert_sl_dl_KitchenFloor[];
extern Gfx mat_sl_dl_LoungeWall_001[];
extern Gfx mat_revert_sl_dl_LoungeWall_001[];
extern Gfx mat_sl_dl_LoungeFloor_001[];
extern Gfx mat_revert_sl_dl_LoungeFloor_001[];
extern Gfx mat_sl_dl_HalfPillar_001[];
extern Gfx mat_revert_sl_dl_HalfPillar_001[];
extern Gfx mat_sl_dl_GameRoomWall_002[];
extern Gfx mat_revert_sl_dl_GameRoomWall_002[];
extern Gfx mat_sl_dl_GameRoomCarpet_002[];
extern Gfx mat_revert_sl_dl_GameRoomCarpet_002[];
extern Gfx mat_sl_dl_CarpetEnd[];
extern Gfx mat_revert_sl_dl_CarpetEnd[];
extern Gfx mat_sl_dl_GWall_v4_001[];
extern Gfx mat_revert_sl_dl_GWall_v4_001[];
extern Gfx mat_sl_dl_GFloor_v4_001[];
extern Gfx mat_revert_sl_dl_GFloor_v4_001[];
extern Gfx mat_sl_dl_BedroomWall[];
extern Gfx mat_revert_sl_dl_BedroomWall[];
extern Gfx mat_sl_dl_BedroomFloor[];
extern Gfx mat_revert_sl_dl_BedroomFloor[];
extern Gfx sl_dl_MainHall_mesh_layer_1[];
extern Gfx sl_dl_Hallway_002_mesh_layer_1[];
extern Gfx sl_dl_LivingRoom_mesh_layer_1[];
extern Gfx sl_dl_Kitchen_mesh_layer_1[];
extern Gfx sl_dl_Lounge_mesh_layer_1[];
extern Gfx sl_dl_EntertainmentRoom_mesh_layer_1[];
extern Gfx sl_dl_EntertainmentRoom_mesh_layer_2[];
extern Gfx sl_dl_Basement_mesh_layer_1[];
extern Gfx sl_dl_Bedroom_mesh_layer_1[];
extern Gfx sl_dl_material_revert_render_settings[];
