#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "stomp_smoke/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "boo/geo.inc.c"
#include "haunted_cage/geo.inc.c"

#include "new_koopa/geo.inc.c"
#include "new_shyguy/geo.inc.c"
#include "toad_friend/geo.inc.c"
#include "star_piece/geo.inc.c"
//#include "token/geo.inc.c"
#include "key_small/geo.inc.c"
#include "key_big/geo.inc.c"
#include "boocoin/geo.inc.c"
#include "ghostsand_ball/geo.inc.c"
#include "teleporter/geo.inc.c"
#include "key_broken/geo.inc.c"
#include "lantern/geo.inc.c"

#include "StarCurrency/geo.inc.c"
#include "held_letter/geo.inc.c"
#include "global_gate/geo.inc.c"
#include "horizontal_pole/geo.inc.c"
#include "snufit/geo.inc.c"
#include "garage_wall/geo.inc.c"
#include "journal_book/geo.inc.c"
#include "prospector_t/geo.inc.c"