extern const GeoLayout sauna_grate_switch_opt1[];
extern const GeoLayout sauna_grate_switch_opt2[];
extern const GeoLayout sauna_grate_geo[];
extern Lights1 sauna_grate_Grate_001_layer4_lights;
extern u8 sauna_grate_i8_grate2_i4[];
extern u8 sauna_grate_tv_metal_i8[];
extern u8 sauna_grate_Clown_0Gray_ia8[];
extern u8 sauna_grate_clown_1_ci8[];
extern u8 sauna_grate_clown_1_ci8_pal_rgba16[];
extern u8 sauna_grate_Clown_2Gray_ia8[];
extern Vtx sauna_grate_grate_mesh_layer_4_vtx_0[40];
extern Gfx sauna_grate_grate_mesh_layer_4_tri_0[];
extern Vtx sauna_grate_number_mesh_layer_4_vtx_0[20];
extern Gfx sauna_grate_number_mesh_layer_4_tri_0[];
extern Gfx mat_sauna_grate_Grate_001_layer4[];
extern Gfx mat_revert_sauna_grate_Grate_001_layer4[];
extern Gfx mat_sauna_grate_Clown0[];
extern Gfx mat_revert_sauna_grate_Clown0[];
extern Gfx mat_sauna_grate_Clown1[];
extern Gfx mat_revert_sauna_grate_Clown1[];
extern Gfx mat_sauna_grate_Clown2[];
extern Gfx mat_revert_sauna_grate_Clown2[];
extern Gfx sauna_grate_grate_mesh_layer_4[];
extern Gfx sauna_grate_number_mesh_layer_4[];
extern Gfx sauna_grate_number_mesh_layer_4_mat_override_Clown1_0[];
extern Gfx sauna_grate_number_mesh_layer_4_mat_override_Clown2_1[];
extern Gfx sauna_grate_material_revert_render_settings[];
