extern const GeoLayout pool_ball_bswitch_opt1[];
extern const GeoLayout pool_ball_geo[];
extern u8 pool_ball__8ball_i8[];
extern u8 pool_ball__8ballstripe_i8[];
extern Vtx pool_ball_ball_mesh_layer_1_vtx_0[28];
extern Gfx pool_ball_ball_mesh_layer_1_tri_0[];
extern Gfx mat_pool_ball_Ball[];
extern Gfx mat_revert_pool_ball_Ball[];
extern Gfx mat_pool_ball_BallStripe[];
extern Gfx mat_revert_pool_ball_BallStripe[];
extern Gfx pool_ball_ball_mesh_layer_1[];
extern Gfx pool_ball_ball_mesh_layer_1_mat_override_BallStripe_0[];
extern Gfx pool_ball_material_revert_render_settings[];
