#include "src/game/envfx_snow.h"

const GeoLayout bbh_area_3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(8, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bbh_dl_301__NOP_geo),
			GEO_BRANCH(1, bbh_dl_302__NOP_geo),
			GEO_BRANCH(1, bbh_dl_303__NOP_geo),
			GEO_BRANCH(1, bbh_dl_304__NOP_geo),
			GEO_BRANCH(1, bbh_dl_305__SnowGlobe_geo),
			GEO_BRANCH(1, bbh_dl_306__UnderGlobe_geo),
			GEO_BRANCH(1, bbh_dl_307__Ice_Castle_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_301__NOP_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Snow_008_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_302__NOP_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Snow_007_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_303__NOP_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Snow_006_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_304__NOP_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Snow_005_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_BB_geo[] = {
	GEO_TRANSLATE_NODE(LAYER_OPAQUE, -131072, 0, 0),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT_DECAL, 131072, 0, 0, bbh_dl_BB_mesh_layer_6),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_BB_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_CC_geo[] = {
	GEO_TRANSLATE_NODE(LAYER_OPAQUE, -131072, 0, 0),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 131072, 0, 0, bbh_dl_CC_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_305__SnowGlobe_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_console),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bbh_dl_BB_geo),
			GEO_BRANCH(1, bbh_dl_CC_geo),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 131072, 0, 0, bbh_dl_AA_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_PitPlatforms_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_PitPlatforms_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Bench_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Black_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Castle_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_CastleRuins_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_CastleRuins_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_CastleRuins_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_CastleRuins_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Flower_002_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bbh_dl_Flower_002_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_IcePlatforms_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_IceSlide_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_IceSlide_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_IceSlide_002_mesh_layer_4),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -131072, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(0x2D, geo_set_red_painting),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Painting_001_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Platform_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bbh_dl_Platform_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Slingshot_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Snow_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bbh_dl_Snow_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Snow_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Snow_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_SnowMountain_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_UnderglobeFake_mesh_layer_1),
		GEO_ASM(0, background_translate),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_ZZSky_001_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_306__UnderGlobe_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Y99SlideExt_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Y99SlideExt_mesh_layer_4),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -4946, -1744, -7957),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2048, 3000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Z89Chains_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Z89Platform_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -3671, -1790, -7551),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2048, 3000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Z90Chains_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Z90Platform_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -4148, -1765, -6092),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2048, 3000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Z91Chains_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Z91Platform_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -3444, -1823, -5395),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2048, 3000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Z92Chains_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Z92Platform_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -2031, -1978, -4251),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2048, 4096),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Z93Chains_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Z93Platform_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1054, -2714, -3857),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2048, 4096),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Z94Chains_mesh_layer_4),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_Z94Chains_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Z94Platform_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Z95Platform_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 511, -2714, -1046),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2048, 6144),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Z96Chains_mesh_layer_4),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_Z96Chains_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Z96Platform_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -379, -2799, 600),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2048, 6144),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Z97Chains_mesh_layer_4),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_Z97Chains_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Z97Platform_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Z98Platform_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_Z98Waterfall_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Z99Floor_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Z99Walls_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 131072, 0, 0, bbh_dl_ZZBlackBox2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_FORCE, bbh_dl_ZZZSky_mesh_layer_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_2ref_002_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Castle_011_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Castle_012_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_3ref_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_3ref_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_2ref_003_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -131072, 0, 0),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 131072, 0, 0, bbh_dl_Castle_013_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 131072, 0, 0, bbh_dl_iceplats2_001_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, bbh_dl_iceplats2_001_mesh_layer_2),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_3ref_001_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -131072, 0, 0, bbh_dl_3ref_001_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_2BlackBox1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -131072, 0, 0, bbh_dl_2BlackBox1_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_3BlackBox2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -131072, 0, 0, bbh_dl_3BlackBox2_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_2ref_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 131072, 0, 0),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -131072, 0, 0, bbh_dl_2ref_001_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -131072, 0, 0, bbh_dl_IceSlideEmu_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_3Ref_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_3Ref_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_307__Ice_Castle_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_ice_backroom),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bbh_dl_2ref_002_geo),
			GEO_BRANCH(1, bbh_dl_3ref_geo),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_1Ref_001_mesh_layer_1),
		GEO_SWITCH_CASE(2, geo_switch_ice_somewalls),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bbh_dl_2ref_003_geo),
			GEO_BRANCH(1, bbh_dl_3ref_001_geo),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -131072, 0, 0, bbh_dl_1Ref_002_mesh_layer_1),
		GEO_SWITCH_CASE(2, geo_switch_console),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bbh_dl_2BlackBox1_geo),
			GEO_BRANCH(1, bbh_dl_3BlackBox2_geo),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -131072, 0, 0, bbh_dl_1Ref_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Castle_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Castle_004_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Castle_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Castle_006_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_Castle_007_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bbh_dl_Castle_009_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Crown_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_FancyChair_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_FloorPaintings_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_FloorPaintings_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_iceplats1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, bbh_dl_iceplats1_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_iceplats1_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_iceplats2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, bbh_dl_iceplats2_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_iceplats2_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_icestairs_mesh_layer_1),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1758, 11759, -19293, 0, 155, 0),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 41532),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 4052, 1500, -8267, 0, 155, 0),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 41532),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Paintings_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Paintings_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Paintings_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Platforms_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_Steam_mesh_layer_5),
		GEO_SWITCH_CASE(2, geo_switch_console),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bbh_dl_2ref_geo),
			GEO_BRANCH(1, bbh_dl_3Ref_geo),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_1Ref_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_under_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_area_3[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 150, 45000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 131072, 0, 0, 131072, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bbh_area_3_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_NORMAL, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_FORCE, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bbh_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
