extern const GeoLayout l2_falling_floor_switch_opt1[];
extern const GeoLayout l2_falling_floor_switch_opt2[];
extern const GeoLayout l2_falling_floor_geo[];
extern Lights1 l2_falling_floor_BathroomTiles_001_lights;
extern u8 l2_falling_floor_RockPattern09_ci8[];
extern u8 l2_falling_floor_RockPattern09_ci8_pal_rgba16[];
extern u8 l2_falling_floor_stonetiles_i8[];
extern u8 l2_falling_floor_Glover_0B62F8CF_0_0_B70F30CC_ciByRGBA_lightblue_ci4[];
extern u8 l2_falling_floor_Glover_0B62F8CF_0_0_B70F30CC_ciByRGBA_lightblue_ci4_pal_rgba16[];
extern Vtx l2_falling_floor_ground_mesh_layer_1_vtx_0[32];
extern Gfx l2_falling_floor_ground_mesh_layer_1_tri_0[];
extern Vtx l2_falling_floor_top_mesh_layer_1_vtx_0[8];
extern Gfx l2_falling_floor_top_mesh_layer_1_tri_0[];
extern Gfx mat_l2_falling_floor_Ground_001[];
extern Gfx mat_revert_l2_falling_floor_Ground_001[];
extern Gfx mat_l2_falling_floor_BathroomTiles_001[];
extern Gfx mat_revert_l2_falling_floor_BathroomTiles_001[];
extern Gfx mat_l2_falling_floor_bathroomtiles2[];
extern Gfx mat_l2_falling_floor_bathroomtiles3[];
extern Gfx mat_revert_l2_falling_floor_bathroomtiles3[];
extern Gfx l2_falling_floor_ground_mesh_layer_1[];
extern Gfx l2_falling_floor_top_mesh_layer_1[];
extern Gfx l2_falling_floor_top_mesh_layer_1_mat_override_bathroomtiles2_0[];
extern Gfx l2_falling_floor_top_mesh_layer_1_mat_override_bathroomtiles3_1[];
extern Gfx l2_falling_floor_material_revert_render_settings[];
