extern const GeoLayout wall_goomba_geo[];
extern u8 wall_goomba_goomba_sprite_ci4[];
extern u8 wall_goomba_goomba_sprite_ci4_pal_rgba16[];
extern Vtx wall_goomba_WallGoomba_mesh_layer_4_vtx_cull[8];
extern Vtx wall_goomba_WallGoomba_mesh_layer_4_vtx_0[4];
extern Gfx wall_goomba_WallGoomba_mesh_layer_4_tri_0[];
extern Gfx mat_wall_goomba__2DGoomba[];
extern Gfx mat_revert_wall_goomba__2DGoomba[];
extern Gfx wall_goomba_WallGoomba_mesh_layer_4[];
extern Gfx wall_goomba_material_revert_render_settings[];
