extern const GeoLayout racecar_Ca2[];
extern const GeoLayout racecar_geo[];
extern Lights1 racecar_whomp_f3d_001_lights;
extern Lights1 racecar_thwomp_f3d_001_lights;
extern u8 racecar_car2_ci4[];
extern u8 racecar_car2_ci4_pal_rgba16[];
extern u8 racecar_car1_ci4[];
extern u8 racecar_car1_ci4_pal_rgba16[];
extern Vtx racecar_dl1_mesh_layer_1_vtx_0[47];
extern Gfx racecar_dl1_mesh_layer_1_tri_0[];
extern Vtx racecar_start_dl2_mesh_layer_1_vtx_0[56];
extern Gfx racecar_start_dl2_mesh_layer_1_tri_0[];
extern Gfx mat_racecar_whomp_f3d_001[];
extern Gfx mat_revert_racecar_whomp_f3d_001[];
extern Gfx mat_racecar_thwomp_f3d_001[];
extern Gfx mat_revert_racecar_thwomp_f3d_001[];
extern Gfx racecar_dl1_mesh_layer_1[];
extern Gfx racecar_start_dl2_mesh_layer_1[];
extern Gfx racecar_material_revert_render_settings[];
