extern const GeoLayout boss_graphic_switch_opt1[];
extern const GeoLayout boss_graphic_switch_opt2[];
extern const GeoLayout boss_graphic_geo[];
extern u8 boss_graphic_ci4_pow_graphic_ci4[];
extern u8 boss_graphic_ci4_pow_graphic_ci4_pal_rgba16[];
extern u8 boss_graphic_ci4_bam_graphic_ci4[];
extern u8 boss_graphic_ci4_bam_graphic_ci4_pal_rgba16[];
extern u8 boss_graphic_ci4_wham_graphic_ci4[];
extern u8 boss_graphic_ci4_wham_graphic_ci4_pal_rgba16[];
extern Vtx boss_graphic_graphic_mesh_layer_4_vtx_0[4];
extern Gfx boss_graphic_graphic_mesh_layer_4_tri_0[];
extern Gfx mat_boss_graphic_PowGraphic[];
extern Gfx mat_revert_boss_graphic_PowGraphic[];
extern Gfx mat_boss_graphic_BamGraphic[];
extern Gfx mat_revert_boss_graphic_BamGraphic[];
extern Gfx mat_boss_graphic_WhamGraphic[];
extern Gfx mat_revert_boss_graphic_WhamGraphic[];
extern Gfx boss_graphic_graphic_mesh_layer_4[];
extern Gfx boss_graphic_graphic_mesh_layer_4_mat_override_BamGraphic_0[];
extern Gfx boss_graphic_graphic_mesh_layer_4_mat_override_WhamGraphic_1[];
extern Gfx boss_graphic_material_revert_render_settings[];
