extern const GeoLayout stalactite_geo[];
extern Lights1 stalactite_BackgroundDirt_001_layer1_lights;
extern u8 stalactite_dirt_rubble_i8_64x32_i8[];
extern u8 stalactite_dirt_i8_i8[];
extern Vtx stalactite_stalactite_mesh_layer_1_vtx_cull[8];
extern Vtx stalactite_stalactite_mesh_layer_1_vtx_0[7];
extern Gfx stalactite_stalactite_mesh_layer_1_tri_0[];
extern Gfx mat_stalactite_BackgroundDirt_001_layer1[];
extern Gfx mat_revert_stalactite_BackgroundDirt_001_layer1[];
extern Gfx stalactite_stalactite_mesh_layer_1[];
extern Gfx stalactite_material_revert_render_settings[];
