extern const GeoLayout mind_mound_geo[];
extern u8 mind_mound_i8_cool_bricks_3_inverted_i4[];
extern u8 mind_mound_gold_rock_ground2_bright_i8[];
extern Vtx mind_mound_MindMound_mesh_layer_1_vtx_cull[8];
extern Vtx mind_mound_MindMound_mesh_layer_1_vtx_0[14];
extern Gfx mind_mound_MindMound_mesh_layer_1_tri_0[];
extern Gfx mat_mind_mound_MoundFloor_layer1[];
extern Gfx mat_revert_mind_mound_MoundFloor_layer1[];
extern Gfx mind_mound_MindMound_mesh_layer_1[];
extern Gfx mind_mound_material_revert_render_settings[];
