extern Vtx test_map_TestMap_mesh_vtx_0[4];
extern Gfx test_map_TestMap_mesh_tri_0[];
extern Vtx test_map_TestMap_mesh_vtx_1[16];
extern Gfx test_map_TestMap_mesh_tri_1[];
extern Gfx mat_test_map_Gray[];
extern Gfx mat_revert_test_map_Gray[];
extern Gfx mat_test_map_Border_layer1[];
extern Gfx mat_revert_test_map_Border_layer1[];
extern Gfx test_map_TestMap_mesh[];
