extern const GeoLayout sunblock_Switch_opt1[];
extern const GeoLayout sunblock_geo[];
extern u8 sunblock_sun_symbol2_ci4[];
extern u8 sunblock_sun_symbol2_ci4_pal_rgba16[];
extern Vtx sunblock_H_mesh_layer_4_vtx_0[24];
extern Gfx sunblock_H_mesh_layer_4_tri_0[];
extern Gfx mat_sunblock_Sunblock_001[];
extern Gfx mat_revert_sunblock_Sunblock_001[];
extern Gfx sunblock_H_mesh_layer_4[];
extern Gfx sunblock_material_revert_render_settings[];
