extern const GeoLayout bg_manor_switch_opt1[];
extern const GeoLayout bg_manor_switch_opt2[];
extern const GeoLayout bg_manor_switch_opt3[];
extern const GeoLayout bg_manor_switch_opt4[];
extern const GeoLayout bg_manor_switch_opt5[];
extern const GeoLayout bg_manor_geo[];
extern u8 bg_manor__64x_manor_rgba32[];
extern u8 bg_manor__64x_mainhall_rgba32[];
extern u8 bg_manor__64x_lounge_rgba32[];
extern u8 bg_manor__64x_city_rgba32[];
extern u8 bg_manor__64x_trophy_rgba32[];
extern u8 bg_manor__64x_corridor_rgba32[];
extern Vtx bg_manor_bg_mesh_layer_1_vtx_0[16];
extern Gfx bg_manor_bg_mesh_layer_1_tri_0[];
extern Gfx mat_bg_manor_BG1[];
extern Gfx mat_revert_bg_manor_BG1[];
extern Gfx mat_bg_manor_BG2[];
extern Gfx mat_revert_bg_manor_BG2[];
extern Gfx mat_bg_manor_BG3[];
extern Gfx mat_revert_bg_manor_BG3[];
extern Gfx mat_bg_manor_BG4[];
extern Gfx mat_revert_bg_manor_BG4[];
extern Gfx mat_bg_manor_BG5[];
extern Gfx mat_revert_bg_manor_BG5[];
extern Gfx mat_bg_manor_BG6[];
extern Gfx mat_revert_bg_manor_BG6[];
extern Gfx bg_manor_bg_mesh_layer_1[];
extern Gfx bg_manor_bg_mesh_layer_1_mat_override_BG2_0[];
extern Gfx bg_manor_bg_mesh_layer_1_mat_override_BG3_1[];
extern Gfx bg_manor_bg_mesh_layer_1_mat_override_BG4_2[];
extern Gfx bg_manor_bg_mesh_layer_1_mat_override_BG5_3[];
extern Gfx bg_manor_bg_mesh_layer_1_mat_override_BG6_4[];
extern Gfx bg_manor_material_revert_render_settings[];
