extern const GeoLayout end_goomba_000_switch_001_opt1[];
extern const GeoLayout end_goomba_geo[];
extern u8 end_goomba_BOOGOO1_i4[];
extern u8 end_goomba_BOOGOO2_i4[];
extern Vtx end_goomba_000_displaylist_mesh_layer_1_vtx_0[4];
extern Gfx end_goomba_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx end_goomba_000_offset_002_mesh_layer_1_vtx_0[57];
extern Gfx end_goomba_000_offset_002_mesh_layer_1_tri_0[];
extern Vtx end_goomba_000_offset_003_mesh_layer_1_vtx_0[28];
extern Gfx end_goomba_000_offset_003_mesh_layer_1_tri_0[];
extern Vtx end_goomba_000_offset_004_mesh_layer_1_vtx_0[28];
extern Gfx end_goomba_000_offset_004_mesh_layer_1_tri_0[];
extern Gfx mat_end_goomba_BooGooObj_layer1[];
extern Gfx mat_revert_end_goomba_BooGooObj_layer1[];
extern Gfx mat_end_goomba_BooGooObjTrans_layer1[];
extern Gfx mat_revert_end_goomba_BooGooObjTrans_layer1[];
extern Gfx end_goomba_000_displaylist_mesh_layer_1[];
extern Gfx end_goomba_000_displaylist_mesh_layer_1_mat_override_BooGooObjTrans_0[];
extern Gfx end_goomba_000_offset_002_mesh_layer_1[];
extern Gfx end_goomba_000_offset_002_mesh_layer_1_mat_override_BooGooObjTrans_0[];
extern Gfx end_goomba_000_offset_003_mesh_layer_1[];
extern Gfx end_goomba_000_offset_003_mesh_layer_1_mat_override_BooGooObjTrans_0[];
extern Gfx end_goomba_000_offset_004_mesh_layer_1[];
extern Gfx end_goomba_000_offset_004_mesh_layer_1_mat_override_BooGooObjTrans_0[];
extern Gfx end_goomba_material_revert_render_settings[];
