extern const GeoLayout end_laser_geo[];
extern u8 end_laser_BOOGOO1_i4[];
extern u8 end_laser_BOOGOO2_i4[];
extern Vtx end_laser_Bubble_001_mesh_layer_1_vtx_cull[8];
extern Vtx end_laser_Bubble_001_mesh_layer_1_vtx_0[28];
extern Gfx end_laser_Bubble_001_mesh_layer_1_tri_0[];
extern Gfx mat_end_laser_BooGooObj_layer1[];
extern Gfx mat_revert_end_laser_BooGooObj_layer1[];
extern Gfx end_laser_Bubble_001_mesh_layer_1[];
extern Gfx end_laser_material_revert_render_settings[];
