extern const GeoLayout nice_face_geo[];
extern u8 nice_face_nice_face_ci4[];
extern u8 nice_face_nice_face_ci4_pal_rgba16[];
extern Vtx nice_face_NiceFace_mesh_layer_4_vtx_cull[8];
extern Vtx nice_face_NiceFace_mesh_layer_4_vtx_0[4];
extern Gfx nice_face_NiceFace_mesh_layer_4_tri_0[];
extern Gfx mat_nice_face_NiceFace[];
extern Gfx mat_revert_nice_face_NiceFace[];
extern Gfx nice_face_NiceFace_mesh_layer_4[];
extern Gfx nice_face_material_revert_render_settings[];
