#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/bob/header.h"

#include "levels/bob/chain_chomp_gate/geo.inc.c"
#include "levels/bob/seesaw_platform/geo.inc.c"
#include "levels/bob/grate_door/geo.inc.c"
#include "levels/bob/areas/1/geo.inc.c"
#include "levels/bob/geo.inc.c"

#include "levels/bob/landchunk/geo.inc.c"
#include "levels/bob/chandelier/geo.inc.c"
#include "levels/bob/plate/geo.inc.c"
#include "levels/bob/dining_chair/geo.inc.c"
#include "levels/bob/utencils/geo.inc.c"
#include "levels/bob/teapot/geo.inc.c"
#include "levels/bob/l1_gate/geo.inc.c"
#include "levels/bob/lever/geo.inc.c"
#include "levels/bob/l1_book/geo.inc.c"
#include "levels/bob/L1_burner/geo.inc.c"
#include "levels/bob/l1_cabinet/geo.inc.c"
#include "levels/bob/l1_barrel/geo.inc.c"
#include "levels/bob/l1_loose_shelf/geo.inc.c"
#include "levels/bob/kitchen_fridge/geo.inc.c"
#include "levels/bob/stove_button/geo.inc.c"
#include "levels/bob/frying_pan/geo.inc.c"
#include "levels/bob/remote/geo.inc.c"
#include "levels/bob/tv_static/geo.inc.c"
#include "levels/bob/cushion/geo.inc.c"
#include "levels/bob/l1_thin_book/geo.inc.c"
#include "levels/bob/water_bucket/geo.inc.c"
#include "levels/bob/l1_flip_book/geo.inc.c"
#include "levels/bob/boss_koopa/geo.inc.c"
#include "levels/bob/l1_lock/geo.inc.c"