extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_dl_Room1A_geo[];
extern const GeoLayout bob_dl_Room1B_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const u8 bob_area_1_collision_rooms[];
extern const MacroObject bob_area_1_macro_objs[];
extern Vtx bob_dl_Bookshelf_mesh_vtx_0[60];
extern Gfx bob_dl_Bookshelf_mesh_tri_0[];
extern Vtx bob_dl_Bookshelf_mesh_vtx_1[16];
extern Gfx bob_dl_Bookshelf_mesh_tri_1[];
extern Vtx bob_dl_Dresser_mesh_vtx_0[28];
extern Gfx bob_dl_Dresser_mesh_tri_0[];
extern Vtx bob_dl_Dresser_mesh_vtx_1[4];
extern Gfx bob_dl_Dresser_mesh_tri_1[];
extern Vtx bob_dl_Lamp_mesh_vtx_0[105];
extern Gfx bob_dl_Lamp_mesh_tri_0[];
extern Vtx bob_dl_MRoomCrate_mesh_vtx_0[24];
extern Gfx bob_dl_MRoomCrate_mesh_tri_0[];
extern Vtx bob_dl_MRoomCrate_001_mesh_vtx_0[24];
extern Gfx bob_dl_MRoomCrate_001_mesh_tri_0[];
extern Vtx bob_dl_MRoomCrate_002_mesh_vtx_0[24];
extern Gfx bob_dl_MRoomCrate_002_mesh_tri_0[];
extern Vtx bob_dl_MRoomCrate_003_mesh_vtx_0[24];
extern Gfx bob_dl_MRoomCrate_003_mesh_tri_0[];
extern Vtx bob_dl_MRoomCrate_004_mesh_vtx_0[24];
extern Gfx bob_dl_MRoomCrate_004_mesh_tri_0[];
extern Vtx bob_dl_Mudroom_mesh_vtx_0[28];
extern Gfx bob_dl_Mudroom_mesh_tri_0[];
extern Vtx bob_dl_Mudroom_mesh_vtx_1[127];
extern Gfx bob_dl_Mudroom_mesh_tri_1[];
extern Vtx bob_dl_Mudroom_001_mesh_vtx_0[4];
extern Gfx bob_dl_Mudroom_001_mesh_tri_0[];
extern Vtx bob_dl_Mudroom_002_mesh_vtx_0[24];
extern Gfx bob_dl_Mudroom_002_mesh_tri_0[];
extern Vtx bob_dl_Mudroom_003_mesh_vtx_0[9];
extern Gfx bob_dl_Mudroom_003_mesh_tri_0[];
extern Vtx bob_dl_LandChunk_mesh_vtx_0[5];
extern Gfx bob_dl_LandChunk_mesh_tri_0[];
extern Vtx bob_dl_LandChunk_mesh_vtx_1[20];
extern Gfx bob_dl_LandChunk_mesh_tri_1[];
extern Vtx bob_dl_LandChunk_001_mesh_vtx_0[5];
extern Gfx bob_dl_LandChunk_001_mesh_tri_0[];
extern Vtx bob_dl_LandChunk_001_mesh_vtx_1[20];
extern Gfx bob_dl_LandChunk_001_mesh_tri_1[];
extern Vtx bob_dl_MRoomCrate_005_mesh_vtx_0[24];
extern Gfx bob_dl_MRoomCrate_005_mesh_tri_0[];
extern Vtx bob_dl_MRoomCrate_006_mesh_vtx_0[24];
extern Gfx bob_dl_MRoomCrate_006_mesh_tri_0[];
extern Vtx bob_dl_MRoomCrate_007_mesh_vtx_0[24];
extern Gfx bob_dl_MRoomCrate_007_mesh_tri_0[];
extern Vtx bob_dl_MRoomCrate_008_mesh_vtx_0[24];
extern Gfx bob_dl_MRoomCrate_008_mesh_tri_0[];
extern Vtx bob_dl_MainHall_mesh_vtx_0[15];
extern Gfx bob_dl_MainHall_mesh_tri_0[];
extern Vtx bob_dl_MainHall_mesh_vtx_1[24];
extern Gfx bob_dl_MainHall_mesh_tri_1[];
extern Vtx bob_dl_MainHall_mesh_vtx_2[32];
extern Gfx bob_dl_MainHall_mesh_tri_2[];
extern Vtx bob_dl_MainHall_001_mesh_vtx_0[44];
extern Gfx bob_dl_MainHall_001_mesh_tri_0[];
extern Vtx bob_dl_MainHall_002_mesh_vtx_0[4];
extern Gfx bob_dl_MainHall_002_mesh_tri_0[];
extern Vtx bob_dl_MainHall_003_mesh_vtx_0[4];
extern Gfx bob_dl_MainHall_003_mesh_tri_0[];
extern Vtx bob_dl_Pillar_mesh_vtx_0[118];
extern Gfx bob_dl_Pillar_mesh_tri_0[];

extern Gfx bob_dl_Bookshelf_mesh[];
extern Gfx bob_dl_Dresser_mesh[];
extern Gfx bob_dl_Lamp_mesh[];
extern Gfx bob_dl_MRoomCrate_mesh[];
extern Gfx bob_dl_MRoomCrate_001_mesh[];
extern Gfx bob_dl_MRoomCrate_002_mesh[];
extern Gfx bob_dl_MRoomCrate_003_mesh[];
extern Gfx bob_dl_MRoomCrate_004_mesh[];
extern Gfx bob_dl_Mudroom_mesh[];
extern Gfx bob_dl_Mudroom_001_mesh[];
extern Gfx bob_dl_Mudroom_002_mesh[];
extern Gfx bob_dl_Mudroom_003_mesh[];
extern Gfx bob_dl_LandChunk_mesh[];
extern Gfx bob_dl_LandChunk_001_mesh[];
extern Gfx bob_dl_MRoomCrate_005_mesh[];
extern Gfx bob_dl_MRoomCrate_006_mesh[];
extern Gfx bob_dl_MRoomCrate_007_mesh[];
extern Gfx bob_dl_MRoomCrate_008_mesh[];
extern Gfx bob_dl_MainHall_mesh[];
extern Gfx bob_dl_MainHall_001_mesh[];
extern Gfx bob_dl_MainHall_002_mesh[];
extern Gfx bob_dl_MainHall_003_mesh[];
extern Gfx bob_dl_Pillar_mesh[];
extern Gfx bob_dl_material_revert_render_settings[];

