extern const GeoLayout city_bridge2_geo[];
extern u8 city_bridge2_i8_hd_lego_i4[];
extern u8 city_bridge2_lego_colors2_rgba16[];
extern Vtx city_bridge2_Bridge_001_mesh_layer_1_vtx_cull[8];
extern Vtx city_bridge2_Bridge_001_mesh_layer_1_vtx_0[42];
extern Gfx city_bridge2_Bridge_001_mesh_layer_1_tri_0[];
extern Gfx mat_city_bridge2_LegoWallNoWarp_layer1[];
extern Gfx mat_revert_city_bridge2_LegoWallNoWarp_layer1[];
extern Gfx city_bridge2_Bridge_001_mesh_layer_1[];
extern Gfx city_bridge2_material_revert_render_settings[];
