extern const GeoLayout new_chase_pieces_CToL_001[];
extern const GeoLayout new_chase_pieces_RToL_001[];
extern const GeoLayout new_chase_pieces_LToC[];
extern const GeoLayout new_chase_pieces_CToC[];
extern const GeoLayout new_chase_pieces_RToC[];
extern const GeoLayout new_chase_pieces_LToR_001[];
extern const GeoLayout new_chase_pieces_CToR[];
extern const GeoLayout new_chase_pieces_RToR_001[];
extern const GeoLayout new_chase_pieces_geo[];
extern u8 new_chase_pieces_patch_dirt4_ci4[];
extern u8 new_chase_pieces_patch_dirt4_ci4_pal_rgba16[];
extern Vtx new_chase_pieces_ll_mesh_layer_1_vtx_0[40];
extern Gfx new_chase_pieces_ll_mesh_layer_1_tri_0[];
extern Vtx new_chase_pieces_start_cl_mesh_layer_1_vtx_0[32];
extern Gfx new_chase_pieces_start_cl_mesh_layer_1_tri_0[];
extern Vtx new_chase_pieces_start_rl_mesh_layer_1_vtx_0[40];
extern Gfx new_chase_pieces_start_rl_mesh_layer_1_tri_0[];
extern Vtx new_chase_pieces_start_lc_mesh_layer_1_vtx_0[40];
extern Gfx new_chase_pieces_start_lc_mesh_layer_1_tri_0[];
extern Vtx new_chase_pieces_start_cc_mesh_layer_1_vtx_0[40];
extern Gfx new_chase_pieces_start_cc_mesh_layer_1_tri_0[];
extern Vtx new_chase_pieces_start_rc_mesh_layer_1_vtx_0[40];
extern Gfx new_chase_pieces_start_rc_mesh_layer_1_tri_0[];
extern Vtx new_chase_pieces_start_lr_mesh_layer_1_vtx_0[54];
extern Gfx new_chase_pieces_start_lr_mesh_layer_1_tri_0[];
extern Vtx new_chase_pieces_start_cr_mesh_layer_1_vtx_0[32];
extern Gfx new_chase_pieces_start_cr_mesh_layer_1_tri_0[];
extern Vtx new_chase_pieces_start_rr_mesh_layer_1_vtx_0[40];
extern Gfx new_chase_pieces_start_rr_mesh_layer_1_tri_0[];
extern Gfx mat_new_chase_pieces_ChamberFloor[];
extern Gfx mat_revert_new_chase_pieces_ChamberFloor[];
extern Gfx new_chase_pieces_ll_mesh_layer_1[];
extern Gfx new_chase_pieces_start_cl_mesh_layer_1[];
extern Gfx new_chase_pieces_start_rl_mesh_layer_1[];
extern Gfx new_chase_pieces_start_lc_mesh_layer_1[];
extern Gfx new_chase_pieces_start_cc_mesh_layer_1[];
extern Gfx new_chase_pieces_start_rc_mesh_layer_1[];
extern Gfx new_chase_pieces_start_lr_mesh_layer_1[];
extern Gfx new_chase_pieces_start_cr_mesh_layer_1[];
extern Gfx new_chase_pieces_start_rr_mesh_layer_1[];
extern Gfx new_chase_pieces_material_revert_render_settings[];
