extern const GeoLayout end_cage_geo[];
extern u8 end_cage_BOOGOO1_i4[];
extern u8 end_cage_BOOGOO2_i4[];
extern Vtx end_cage_Cage_mesh_layer_1_vtx_cull[8];
extern Vtx end_cage_Cage_mesh_layer_1_vtx_0[444];
extern Gfx end_cage_Cage_mesh_layer_1_tri_0[];
extern Gfx mat_end_cage_BooGooObj_layer1[];
extern Gfx mat_revert_end_cage_BooGooObj_layer1[];
extern Gfx end_cage_Cage_mesh_layer_1[];
extern Gfx end_cage_material_revert_render_settings[];
