extern const GeoLayout bedroom_object_2[];
extern const GeoLayout bedroom_object_3[];
extern const GeoLayout bedroom_object_4[];
extern const GeoLayout bedroom_object_geo[];
extern u8 bedroom_object_box_ci4[];
extern u8 bedroom_object_box_ci4_pal_rgba16[];
extern u8 bedroom_object__97500bf2_ci4[];
extern u8 bedroom_object__97500bf2_ci4_pal_rgba16[];
extern u8 bedroom_object_letter_blocks_ci4[];
extern u8 bedroom_object_letter_blocks_ci4_pal_rgba16[];
extern u8 bedroom_object_bookpage_ci8[];
extern u8 bedroom_object_bookpage_ci8_pal_rgba16[];
extern u8 bedroom_object_book_cover2_ci8[];
extern u8 bedroom_object_book_cover2_ci8_pal_rgba16[];
extern Vtx bedroom_object_1_mesh_layer_1_vtx_0[24];
extern Gfx bedroom_object_1_mesh_layer_1_tri_0[];
extern Vtx bedroom_object_Start_2_mesh_layer_1_vtx_0[112];
extern Gfx bedroom_object_Start_2_mesh_layer_1_tri_0[];
extern Vtx bedroom_object_Start_3_mesh_layer_1_vtx_0[24];
extern Gfx bedroom_object_Start_3_mesh_layer_1_tri_0[];
extern Vtx bedroom_object_Start_4_mesh_layer_1_vtx_0[24];
extern Gfx bedroom_object_Start_4_mesh_layer_1_tri_0[];
extern Vtx bedroom_object_Start_4_mesh_layer_1_vtx_1[30];
extern Gfx bedroom_object_Start_4_mesh_layer_1_tri_1[];
extern Gfx mat_bedroom_object_FakeBlock_001[];
extern Gfx mat_revert_bedroom_object_FakeBlock_001[];
extern Gfx mat_bedroom_object_PinkBallFake_001[];
extern Gfx mat_revert_bedroom_object_PinkBallFake_001[];
extern Gfx mat_bedroom_object_LetterBlockFake_001[];
extern Gfx mat_revert_bedroom_object_LetterBlockFake_001[];
extern Gfx mat_bedroom_object_Book_001[];
extern Gfx mat_revert_bedroom_object_Book_001[];
extern Gfx mat_bedroom_object_FakeBookCover_001[];
extern Gfx mat_revert_bedroom_object_FakeBookCover_001[];
extern Gfx bedroom_object_1_mesh_layer_1[];
extern Gfx bedroom_object_Start_2_mesh_layer_1[];
extern Gfx bedroom_object_Start_3_mesh_layer_1[];
extern Gfx bedroom_object_Start_4_mesh_layer_1[];
extern Gfx bedroom_object_material_revert_render_settings[];
