#include "src/game/envfx_snow.h"

const GeoLayout ttm_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, ttm_dl_101__Main_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ttm_dl_101__Main_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ttm_dl_Bottle_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Hallway_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Hallway_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Lava_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Plat_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Shelf_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Simple_Table_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ttm_dl_Simple_Table_003_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Stool_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Straw_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ttm_dl_2dvine_002_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_PlantPlatformsVisuals_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Z4Cloud_025_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Leaf_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Z7Tree_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ttm_dl_Z7Tree_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Z9Ground_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Bathroom_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Platform_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Servant_s_Quarters_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Shelf_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Soap_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_BelowBathroom_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Box_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Pipes_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ttm_dl_Scaffolding_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_Checkered_Goal_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ttm_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_L8_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ttm_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ttm_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ttm_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
