#include "src/game/envfx_snow.h"

const GeoLayout jrb_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(5, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, jrb_dl_101__Garden_geo),
			GEO_BRANCH(1, jrb_dl_102__Dog_House_geo),
			GEO_BRANCH(1, jrb_dl_103__Underground_geo),
			GEO_BRANCH(1, jrb_dl_104__Conservatory_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_dl_101__Garden_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -4929, -388, -753, jrb_dl_DogHouseExterior_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -4929, -388, -753, jrb_dl_DogHouseExterior_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, -488, 0, jrb_dl_Ground_001_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, jrb_dl_Ground_001_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 869, -488, 1108, jrb_dl_Poochy_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, jrb_dl_Poochy_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(4, -1097, -388, -1984, jrb_dl_TallGrass_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(4, -2031, -388, -1016, jrb_dl_TallGrass_001_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(4, 2679, -388, 2189, jrb_dl_TallGrass_002_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(4, -5588, -388, 2560, jrb_dl_TallGrass_003_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_dl_102__Dog_House_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -4929, -388, -8753, jrb_dl_DogHouseExterior_003_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_dl_103__Underground_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -2046, -1731, 2958, jrb_dl_Cave_003_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, 380, 0, jrb_dl_Ground_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, 380, 0, jrb_dl_Ground_003_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_dl_104__Conservatory_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -3630, 1012, 7489, jrb_dl_Conservatory_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, jrb_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(4, jrb_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, jrb_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
