#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/hmc/header.h"

#include "levels/hmc/areas/1/grill_door/geo.inc.c"
#include "levels/hmc/rolling_rock/geo.inc.c"
#include "levels/hmc/rolling_rock_fragment_1/geo.inc.c"
#include "levels/hmc/rolling_rock_fragment_2/geo.inc.c"
#include "levels/hmc/arrow_platform/geo.inc.c"
#include "levels/hmc/arrow_platform_button/geo.inc.c"
#include "levels/hmc/elevator_platform/geo.inc.c"
#include "levels/hmc/areas/1/geo.inc.c"

#include "levels/hmc/geo.inc.c"

#include "levels/hmc/dice_enemy/geo.inc.c"
#include "levels/hmc/pool_ball/geo.inc.c"
#include "levels/hmc/pool_cue/geo.inc.c"
#include "levels/hmc/pool_barrier/geo.inc.c"
#include "levels/hmc/pool_floor/geo.inc.c"
#include "levels/hmc/toy_mole/geo.inc.c"
#include "levels/hmc/mole_cage/geo.inc.c"
#include "levels/hmc/pingpong_ball/geo.inc.c"
#include "levels/hmc/pingpong_paddle/geo.inc.c"
#include "levels/hmc/trophy_octogon/geo.inc.c"
#include "levels/hmc/trophy_rectangle/geo.inc.c"
#include "levels/hmc/music_insts/geo.inc.c"
#include "levels/hmc/foreroom_object/geo.inc.c"
#include "levels/hmc/foreroom_lever/geo.inc.c"
#include "levels/hmc/foreroom_window/geo.inc.c"
#include "levels/hmc/tight_rope/geo.inc.c"