extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_dl_101__OpeningHall_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const u8 hmc_area_1_collision_rooms[];
extern const MacroObject hmc_area_1_macro_objs[];
extern Lights1 hmc_dl_WoodFloor_layer1_lights;
extern Lights1 hmc_dl_Wall_layer1_lights;
extern Lights1 hmc_dl_BooGoo_layer1_lights;
extern u8 hmc_dl_deepplanks_mixed2_rgba16[];
extern u8 hmc_dl_i4_matt_multitex_i4[];
extern u8 hmc_dl_shortbluewall_rgba16[];
extern u8 hmc_dl_cracked_multitex_i4[];
extern u8 hmc_dl_BOOGOO1_i4[];
extern u8 hmc_dl_BOOGOO2_i4[];
extern Vtx hmc_dl_ArtTest_001_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_ArtTest_001_mesh_layer_1_vtx_0[88];
extern Gfx hmc_dl_ArtTest_001_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_ArtTest_001_mesh_layer_1_vtx_1[54];
extern Gfx hmc_dl_ArtTest_001_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_ArtTest_001_mesh_layer_1_vtx_2[4];
extern Gfx hmc_dl_ArtTest_001_mesh_layer_1_tri_2[];
extern Vtx hmc_dl_Floor3_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_Floor3_mesh_layer_1_vtx_0[52];
extern Gfx hmc_dl_Floor3_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_OpeningHall_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_OpeningHall_mesh_layer_1_vtx_0[54];
extern Gfx hmc_dl_OpeningHall_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_OpeningHall_mesh_layer_1_vtx_1[8];
extern Gfx hmc_dl_OpeningHall_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_Stairs_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_Stairs_mesh_layer_1_vtx_0[34];
extern Gfx hmc_dl_Stairs_mesh_layer_1_tri_0[];
extern Gfx mat_hmc_dl_WoodFloor_layer1[];
extern Gfx mat_revert_hmc_dl_WoodFloor_layer1[];
extern Gfx mat_hmc_dl_Wall_layer1[];
extern Gfx mat_revert_hmc_dl_Wall_layer1[];
extern Gfx mat_hmc_dl_BooGoo_layer1[];
extern Gfx mat_revert_hmc_dl_BooGoo_layer1[];
extern Gfx hmc_dl_ArtTest_001_mesh_layer_1[];
extern Gfx hmc_dl_Floor3_mesh_layer_1[];
extern Gfx hmc_dl_OpeningHall_mesh_layer_1[];
extern Gfx hmc_dl_Stairs_mesh_layer_1[];
extern Gfx hmc_dl_material_revert_render_settings[];
