extern const GeoLayout pool_barrier_geo[];
extern Lights1 pool_barrier_GhostBarrier_layer5_lights;
extern u8 pool_barrier_BOOGOO_highcontrast1_i4[];
extern u8 pool_barrier_BOOGOO_highcontrast2_brighterdarks_i4[];
extern Vtx pool_barrier_barrier_mesh_layer_5_vtx_0[18];
extern Gfx pool_barrier_barrier_mesh_layer_5_tri_0[];
extern Gfx mat_pool_barrier_GhostBarrier_layer5[];
extern Gfx mat_revert_pool_barrier_GhostBarrier_layer5[];
extern Gfx pool_barrier_barrier_mesh_layer_5[];
extern Gfx pool_barrier_material_revert_render_settings[];
