extern const GeoLayout pool_barrier_switch_opt1[];
extern const GeoLayout pool_barrier_geo[];
extern u8 pool_barrier_BOOGOO_highcontrast1_i4[];
extern u8 pool_barrier_BOOGOO_highcontrast2_brighterdarks_i4[];
extern Vtx pool_barrier_barrier_mesh_layer_1_vtx_0[18];
extern Gfx pool_barrier_barrier_mesh_layer_1_tri_0[];
extern Vtx pool_barrier_barrier_mesh_layer_1_vtx_1[4];
extern Gfx pool_barrier_barrier_mesh_layer_1_tri_1[];
extern Gfx mat_pool_barrier_GhostBarrier_layer1[];
extern Gfx mat_revert_pool_barrier_GhostBarrier_layer1[];
extern Gfx mat_pool_barrier_GhostBarrierConsole_layer1[];
extern Gfx mat_revert_pool_barrier_GhostBarrierConsole_layer1[];
extern Gfx pool_barrier_barrier_mesh_layer_1[];
extern Gfx pool_barrier_barrier_mesh_layer_1_mat_override_GhostBarrierConsole_0[];
extern Gfx pool_barrier_material_revert_render_settings[];
