extern const GeoLayout new_remote_Switch_opt1[];
extern const GeoLayout new_remote_geo[];
extern Lights1 new_remote_Remote_003_lights;
extern Lights1 new_remote_GrayRemote_001_lights;
extern u8 new_remote_ci4_remote_ci4[];
extern u8 new_remote_ci4_remote_ci4_pal_rgba16[];
extern u8 new_remote_i8_remote2_i8[];
extern Vtx new_remote_Remote_mesh_layer_1_vtx_0[24];
extern Gfx new_remote_Remote_mesh_layer_1_tri_0[];
extern Gfx mat_new_remote_Remote_003[];
extern Gfx mat_revert_new_remote_Remote_003[];
extern Gfx mat_new_remote_GrayRemote_001[];
extern Gfx new_remote_Remote_mesh_layer_1[];
extern Gfx new_remote_Remote_mesh_layer_1_mat_override_GrayRemote_001_0[];
extern Gfx new_remote_material_revert_render_settings[];
