extern const GeoLayout ghost_barrier_geo[];
extern Lights1 ghost_barrier_GhostBarrier_001_lights;
extern u8 ghost_barrier_ghostbarrier_i8[];
extern Vtx ghost_barrier_Decal_mesh_layer_6_vtx_0[8];
extern Gfx ghost_barrier_Decal_mesh_layer_6_tri_0[];
extern Vtx ghost_barrier_Trans_mesh_layer_5_vtx_0[8];
extern Gfx ghost_barrier_Trans_mesh_layer_5_tri_0[];
extern Gfx mat_ghost_barrier_GhostBarrier_001[];
extern Gfx mat_revert_ghost_barrier_GhostBarrier_001[];
extern Gfx ghost_barrier_Decal_mesh_layer_6[];
extern Gfx ghost_barrier_Trans_mesh_layer_5[];
extern Gfx ghost_barrier_material_revert_render_settings[];
