extern const GeoLayout moving_vine_geo[];
extern Lights1 moving_vine_Vine_001_lights;
extern u8 moving_vine_vine_ci8[];
extern u8 moving_vine_vine_ci8_pal_rgba16[];
extern Vtx moving_vine_Vine_mesh_layer_1_vtx_0[45];
extern Gfx moving_vine_Vine_mesh_layer_1_tri_0[];
extern Gfx mat_moving_vine_Vine_001[];
extern Gfx mat_revert_moving_vine_Vine_001[];
extern Gfx moving_vine_Vine_mesh_layer_1[];
extern Gfx moving_vine_material_revert_render_settings[];
