extern const GeoLayout bar_stool_switch_opt1[];
extern const GeoLayout bar_stool_geo[];
extern u8 bar_stool_i8_mat_i8[];
extern u8 bar_stool_metal_circle_i8[];
extern Vtx bar_stool_stool_mesh_layer_1_vtx_0[12];
extern Gfx bar_stool_stool_mesh_layer_1_tri_0[];
extern Vtx bar_stool_stool_mesh_layer_1_vtx_1[14];
extern Gfx bar_stool_stool_mesh_layer_1_tri_1[];
extern Gfx mat_bar_stool_Stool[];
extern Gfx mat_revert_bar_stool_Stool[];
extern Gfx mat_bar_stool_Metal[];
extern Gfx mat_revert_bar_stool_Metal[];
extern Gfx mat_bar_stool_StoolRed[];
extern Gfx mat_revert_bar_stool_StoolRed[];
extern Gfx bar_stool_stool_mesh_layer_1[];
extern Gfx bar_stool_stool_mesh_layer_1_mat_override_StoolRed_0[];
extern Gfx bar_stool_material_revert_render_settings[];
