extern const GeoLayout basement_switch_geo[];
extern Lights1 basement_switch_SwitchEdge_layer1_lights;
extern Lights1 basement_switch_Switch_layer1_lights;
extern u8 basement_switch_switch_rim_ci4[];
extern u8 basement_switch_switch_rim_ci4_pal_rgba16[];
extern u8 basement_switch_switch_exclamation_ia8[];
extern Vtx basement_switch_switch_mesh_layer_1_vtx_0[16];
extern Gfx basement_switch_switch_mesh_layer_1_tri_0[];
extern Vtx basement_switch_switch_mesh_layer_1_vtx_1[4];
extern Gfx basement_switch_switch_mesh_layer_1_tri_1[];
extern Gfx mat_basement_switch_SwitchEdge_layer1[];
extern Gfx mat_revert_basement_switch_SwitchEdge_layer1[];
extern Gfx mat_basement_switch_Switch_layer1[];
extern Gfx mat_revert_basement_switch_Switch_layer1[];
extern Gfx basement_switch_switch_mesh_layer_1[];
extern Gfx basement_switch_material_revert_render_settings[];
