extern const GeoLayout sawblade_SawbladeNoBlood_001[];
extern const GeoLayout sawblade_geo[];
extern u8 sawblade_smw_saws_full_ci4[];
extern u8 sawblade_smw_saws_full_ci4_pal_rgba16[];
extern Vtx sawblade_blade_mesh_layer_4_vtx_0[4];
extern Gfx sawblade_blade_mesh_layer_4_tri_0[];
extern Vtx sawblade_start_blade2_mesh_layer_4_vtx_0[4];
extern Gfx sawblade_start_blade2_mesh_layer_4_tri_0[];
extern Gfx mat_sawblade_Sawblade2D[];
extern Gfx mat_revert_sawblade_Sawblade2D[];
extern Gfx sawblade_blade_mesh_layer_4[];
extern Gfx sawblade_start_blade2_mesh_layer_4[];
extern Gfx sawblade_material_revert_render_settings[];
