extern const GeoLayout winking_moon_switch_opt1[];
extern const GeoLayout winking_moon_geo[];
extern u8 winking_moon_ci4_moon_ci4[];
extern u8 winking_moon_ci4_moon_ci4_pal_rgba16[];
extern u8 winking_moon_spooky_face_ci4[];
extern u8 winking_moon_spooky_face_ci4_pal_rgba16[];
extern u8 winking_moon_wink_face_ci4[];
extern u8 winking_moon_wink_face_ci4_pal_rgba16[];
extern Vtx winking_moon_moon_mesh_layer_4_vtx_0[24];
extern Gfx winking_moon_moon_mesh_layer_4_tri_0[];
extern Vtx winking_moon_moon_mesh_layer_6_vtx_0[16];
extern Gfx winking_moon_moon_mesh_layer_6_tri_0[];
extern Gfx mat_winking_moon_Moon_001[];
extern Gfx mat_revert_winking_moon_Moon_001[];
extern Gfx mat_winking_moon_SpookyFaceMoon[];
extern Gfx mat_revert_winking_moon_SpookyFaceMoon[];
extern Gfx mat_winking_moon_WinkFaceMoon[];
extern Gfx mat_revert_winking_moon_WinkFaceMoon[];
extern Gfx winking_moon_moon_mesh_layer_4[];
extern Gfx winking_moon_moon_mesh_layer_4_mat_override_WinkFaceMoon_0[];
extern Gfx winking_moon_moon_mesh_layer_6[];
extern Gfx winking_moon_moon_mesh_layer_6_mat_override_WinkFaceMoon_0[];
extern Gfx winking_moon_material_revert_render_settings[];
