#include "src/game/envfx_snow.h"

const GeoLayout treehouse_spike_geo[] = {
	GEO_CULLING_RADIUS(4096),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, treehouse_spike_SpikeBody_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, treehouse_spike_SpikeLArm_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 40, 43, -5, treehouse_spike_SpikeLArm_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, treehouse_spike_SpikeLLeg_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 20, -22, -10, treehouse_spike_SpikeLLeg_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, treehouse_spike_SpikeRArm_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -40, 43, -6, treehouse_spike_SpikeRArm_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, treehouse_spike_SpikeRLeg_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -20, -22, -9, treehouse_spike_SpikeRLeg_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 137, 20, NULL),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_update_spike_log),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, treehouse_spike_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
