extern const GeoLayout new_shyguy_group_switch_opt1[];
extern const GeoLayout new_shyguy_group_geo[];
extern Lights1 new_shyguy_group_Shyguy1_001_lights;
extern Lights1 new_shyguy_group_Shyguy2_001_lights;
extern u8 new_shyguy_group_shyguy1_black_i8[];
extern u8 new_shyguy_group_shyguy2_ci8[];
extern u8 new_shyguy_group_shyguy2_ci8_pal_rgba16[];
extern Vtx new_shyguy_group_group_mesh_layer_1_vtx_0[48];
extern Gfx new_shyguy_group_group_mesh_layer_1_tri_0[];
extern Vtx new_shyguy_group_group_mesh_layer_1_vtx_1[323];
extern Gfx new_shyguy_group_group_mesh_layer_1_tri_1[];
extern Vtx new_shyguy_group_group_mesh_layer_1_vtx_2[269];
extern Gfx new_shyguy_group_group_mesh_layer_1_tri_2[];
extern Gfx mat_new_shyguy_group_Shyguy1_001[];
extern Gfx mat_new_shyguy_group_Shyguy2_001[];
extern Gfx mat_revert_new_shyguy_group_Shyguy2_001[];
extern Gfx mat_new_shyguy_group_Black[];
extern Gfx new_shyguy_group_group_mesh_layer_1[];
extern Gfx new_shyguy_group_material_revert_render_settings[];
