extern const GeoLayout obs_boogoo_switch_opt1[];
extern const GeoLayout obs_boogoo_geo[];
extern u8 obs_boogoo_BOOGOO1_i4[];
extern u8 obs_boogoo_BOOGOO2_i4[];
extern Vtx obs_boogoo_obsb_mesh_layer_1_vtx_0[13];
extern Gfx obs_boogoo_obsb_mesh_layer_1_tri_0[];
extern Gfx mat_obs_boogoo_BooGooObject_layer1[];
extern Gfx mat_revert_obs_boogoo_BooGooObject_layer1[];
extern Gfx mat_obs_boogoo_BooGooObjectTrans_layer1[];
extern Gfx mat_revert_obs_boogoo_BooGooObjectTrans_layer1[];
extern Gfx obs_boogoo_obsb_mesh_layer_1[];
extern Gfx obs_boogoo_obsb_mesh_layer_1_mat_override_BooGooObjectTrans_0[];
extern Gfx obs_boogoo_material_revert_render_settings[];
