extern const GeoLayout heavyswitch_Switch_opt1[];
extern const GeoLayout heavyswitch_Switch_opt2[];
extern const GeoLayout heavyswitch_geo[];
extern Lights1 heavyswitch_RedSwitch_001_lights;
extern Lights1 heavyswitch_BlueSwitch_lights;
extern Lights1 heavyswitch_YellowSwitch_lights;
extern u8 heavyswitch_redswitch_ci4[];
extern u8 heavyswitch_redswitch_ci4_pal_rgba16[];
extern u8 heavyswitch_blueswitch_ci4[];
extern u8 heavyswitch_blueswitch_ci4_pal_rgba16[];
extern u8 heavyswitch_yellowswitch_ci4[];
extern u8 heavyswitch_yellowswitch_ci4_pal_rgba16[];
extern Vtx heavyswitch_Group_mesh_layer_1_vtx_0[20];
extern Gfx heavyswitch_Group_mesh_layer_1_tri_0[];
extern Gfx mat_heavyswitch_RedSwitch_001[];
extern Gfx mat_revert_heavyswitch_RedSwitch_001[];
extern Gfx mat_heavyswitch_BlueSwitch[];
extern Gfx mat_revert_heavyswitch_BlueSwitch[];
extern Gfx mat_heavyswitch_YellowSwitch[];
extern Gfx mat_revert_heavyswitch_YellowSwitch[];
extern Gfx heavyswitch_Group_mesh_layer_1[];
extern Gfx heavyswitch_Group_mesh_layer_1_mat_override_BlueSwitch_0[];
extern Gfx heavyswitch_Group_mesh_layer_1_mat_override_YellowSwitch_1[];
extern Gfx heavyswitch_material_revert_render_settings[];
