extern const GeoLayout c2_moving_vine_geo[];
extern Lights1 c2_moving_vine_Vine_002_lights;
extern u8 c2_moving_vine_vine_ci8[];
extern u8 c2_moving_vine_vine_ci8_pal_rgba16[];
extern Vtx c2_moving_vine_Vine_mesh_layer_1_vtx_0[26];
extern Gfx c2_moving_vine_Vine_mesh_layer_1_tri_0[];
extern Gfx mat_c2_moving_vine_Vine_002[];
extern Gfx mat_revert_c2_moving_vine_Vine_002[];
extern Gfx c2_moving_vine_Vine_mesh_layer_1[];
extern Gfx c2_moving_vine_material_revert_render_settings[];
