extern const GeoLayout mirror_switch_Switch_opt1[];
extern const GeoLayout mirror_switch_Switch_opt2[];
extern const GeoLayout mirror_switch_geo[];
extern Lights1 mirror_switch_OrangeSwitch_lights;
extern Lights1 mirror_switch_TealSwitch_lights;
extern Lights1 mirror_switch_PurpleSwitch_lights;
extern u8 mirror_switch_orangeswitch_ci8[];
extern u8 mirror_switch_orangeswitch_ci8_pal_rgba16[];
extern u8 mirror_switch_tealswitch_ci8[];
extern u8 mirror_switch_tealswitch_ci8_pal_rgba16[];
extern u8 mirror_switch_purpleswitch_ci8[];
extern u8 mirror_switch_purpleswitch_ci8_pal_rgba16[];
extern Vtx mirror_switch_Group_mesh_layer_1_vtx_0[20];
extern Gfx mirror_switch_Group_mesh_layer_1_tri_0[];
extern Gfx mat_mirror_switch_OrangeSwitch[];
extern Gfx mat_revert_mirror_switch_OrangeSwitch[];
extern Gfx mat_mirror_switch_TealSwitch[];
extern Gfx mat_revert_mirror_switch_TealSwitch[];
extern Gfx mat_mirror_switch_PurpleSwitch[];
extern Gfx mat_revert_mirror_switch_PurpleSwitch[];
extern Gfx mirror_switch_Group_mesh_layer_1[];
extern Gfx mirror_switch_Group_mesh_layer_1_mat_override_TealSwitch_0[];
extern Gfx mirror_switch_Group_mesh_layer_1_mat_override_PurpleSwitch_1[];
extern Gfx mirror_switch_material_revert_render_settings[];
