extern const GeoLayout cardboard_wall_CBWall2[];
extern const GeoLayout cardboard_wall_geo[];
extern Lights1 cardboard_wall_Cardboard_002_lights;
extern u8 cardboard_wall_cardboard3_ci4[];
extern u8 cardboard_wall_cardboard3_ci4_pal_rgba16[];
extern Vtx cardboard_wall_dl_mesh_layer_1_vtx_0[16];
extern Gfx cardboard_wall_dl_mesh_layer_1_tri_0[];
extern Vtx cardboard_wall_start_dl2_mesh_layer_1_vtx_0[20];
extern Gfx cardboard_wall_start_dl2_mesh_layer_1_tri_0[];
extern Gfx mat_cardboard_wall_Cardboard_002[];
extern Gfx mat_revert_cardboard_wall_Cardboard_002[];
extern Gfx cardboard_wall_dl_mesh_layer_1[];
extern Gfx cardboard_wall_start_dl2_mesh_layer_1[];
extern Gfx cardboard_wall_material_revert_render_settings[];
