extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_dl_01__Lounge_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const u8 wf_area_1_collision_rooms[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_Gate1_lights;
extern Lights1 wf_dl_Gate3_lights;
extern Lights1 wf_dl_Gate2_lights;
extern Lights1 wf_dl_WoodFloor_lights;
extern Lights1 wf_dl_LoungeFloor_lights;
extern Lights1 wf_dl_HallWall_lights;
extern Lights1 wf_dl_LoungeWall_lights;
extern u8 wf_dl_wood_flooring_ci4[];
extern u8 wf_dl_wood_flooring_ci4_pal_rgba16[];
extern u8 wf_dl_i8_polkadot_i8[];
extern u8 wf_dl_ci4_hallway_wall3_ci4[];
extern u8 wf_dl_ci4_hallway_wall3_ci4_pal_rgba16[];
extern u8 wf_dl_i8_wallpaper4_i8[];
extern Vtx wf_dl_Gate_Indicator_mesh_vtx_0[16];
extern Gfx wf_dl_Gate_Indicator_mesh_tri_0[];
extern Vtx wf_dl_Gate_Indicator_001_mesh_vtx_0[4];
extern Gfx wf_dl_Gate_Indicator_001_mesh_tri_0[];
extern Vtx wf_dl_Gate_Indicator_001_mesh_vtx_1[4];
extern Gfx wf_dl_Gate_Indicator_001_mesh_tri_1[];
extern Vtx wf_dl_Hallway_mesh_vtx_0[14];
extern Gfx wf_dl_Hallway_mesh_tri_0[];
extern Vtx wf_dl_Hallway_mesh_vtx_1[8];
extern Gfx wf_dl_Hallway_mesh_tri_1[];
extern Vtx wf_dl_Hallway_mesh_vtx_2[54];
extern Gfx wf_dl_Hallway_mesh_tri_2[];
extern Vtx wf_dl_Hallway_mesh_vtx_3[48];
extern Gfx wf_dl_Hallway_mesh_tri_3[];
extern Vtx wf_dl_ToFloor1_mesh_vtx_0[12];
extern Gfx wf_dl_ToFloor1_mesh_tri_0[];
extern Vtx wf_dl_ToFloor1_mesh_vtx_1[48];
extern Gfx wf_dl_ToFloor1_mesh_tri_1[];
extern Gfx mat_wf_dl_Gate1[];
extern Gfx mat_wf_dl_Gate3[];
extern Gfx mat_wf_dl_Gate2[];
extern Gfx mat_wf_dl_WoodFloor[];
extern Gfx mat_revert_wf_dl_WoodFloor[];
extern Gfx mat_wf_dl_LoungeFloor[];
extern Gfx mat_revert_wf_dl_LoungeFloor[];
extern Gfx mat_wf_dl_HallWall[];
extern Gfx mat_revert_wf_dl_HallWall[];
extern Gfx mat_wf_dl_LoungeWall[];
extern Gfx mat_revert_wf_dl_LoungeWall[];
extern Gfx wf_dl_Gate_Indicator_mesh[];
extern Gfx wf_dl_Gate_Indicator_001_mesh[];
extern Gfx wf_dl_Hallway_mesh[];
extern Gfx wf_dl_ToFloor1_mesh[];
extern Gfx wf_dl_material_revert_render_settings[];
