extern const GeoLayout pingpong_paddle_switch_opt1[];
extern const GeoLayout pingpong_paddle_geo[];
extern Lights1 pingpong_paddle_PaddleRed_layer5_lights;
extern Lights1 pingpong_paddle_TableWood_layer5_lights;
extern Lights1 pingpong_paddle_PaddleBlue_layer5_lights;
extern u8 pingpong_paddle_i8_pingpongpaddle_i8[];
extern u8 pingpong_paddle_darkhallwood_ci8[];
extern u8 pingpong_paddle_darkhallwood_ci8_pal_rgba16[];
extern Vtx pingpong_paddle_paddle_mesh_layer_5_vtx_0[59];
extern Gfx pingpong_paddle_paddle_mesh_layer_5_tri_0[];
extern Vtx pingpong_paddle_paddle_mesh_layer_5_vtx_1[32];
extern Gfx pingpong_paddle_paddle_mesh_layer_5_tri_1[];
extern Gfx mat_pingpong_paddle_PaddleRed_layer5[];
extern Gfx mat_revert_pingpong_paddle_PaddleRed_layer5[];
extern Gfx mat_pingpong_paddle_TableWood_layer5[];
extern Gfx mat_revert_pingpong_paddle_TableWood_layer5[];
extern Gfx mat_pingpong_paddle_PaddleBlue_layer5[];
extern Gfx mat_revert_pingpong_paddle_PaddleBlue_layer5[];
extern Gfx pingpong_paddle_paddle_mesh_layer_5[];
extern Gfx pingpong_paddle_paddle_mesh_layer_5_mat_override_PaddleBlue_0[];
extern Gfx pingpong_paddle_material_revert_render_settings[];
