extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_dl_101__Garden_geo[];
extern const GeoLayout jrb_dl_102__Dog_House_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const u8 jrb_area_1_collision_rooms[];
extern const MacroObject jrb_area_1_macro_objs[];
extern const GeoLayout jrb_area_2_geo[];
extern const GeoLayout jrb_dl_201__Fall_geo[];
extern const GeoLayout jrb_area_2[];
extern const Collision jrb_area_2_collision[];
extern const u8 jrb_area_2_collision_rooms[];
extern const MacroObject jrb_area_2_macro_objs[];
extern Lights1 jrb_dl_Wood_lights;
extern u8 jrb_dl_greenwood_ci4[];
extern u8 jrb_dl_greenwood_ci4_pal_rgba16[];
extern u8 jrb_dl_woodwall_ci8[];
extern u8 jrb_dl_woodwall_ci8_pal_rgba16[];
extern u8 jrb_dl_dark_grass2_ci4[];
extern u8 jrb_dl_dark_grass2_ci4_pal_rgba16[];
extern u8 jrb_dl_Wooden_Fence_1_ci8[];
extern u8 jrb_dl_Wooden_Fence_1_ci8_pal_rgba16[];
extern u8 jrb_dl_forest_wall_ci4[];
extern u8 jrb_dl_forest_wall_ci4_pal_rgba16[];
extern u8 jrb_dl_moon_rgba16[];
extern u8 jrb_dl_night_skybox3_rgba16[];
extern Vtx jrb_dl_DogHouseExterior_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_DogHouseExterior_mesh_layer_1_vtx_0[90];
extern Gfx jrb_dl_DogHouseExterior_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_DogHouseExterior_mesh_layer_1_vtx_1[18];
extern Gfx jrb_dl_DogHouseExterior_mesh_layer_1_tri_1[];
extern Vtx jrb_dl_DogHouseExterior_mesh_layer_1_vtx_2[4];
extern Gfx jrb_dl_DogHouseExterior_mesh_layer_1_tri_2[];
extern Vtx jrb_dl_DogHouseExterior_001_mesh_layer_1_vtx_0[32];
extern Gfx jrb_dl_DogHouseExterior_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Ground_001_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Ground_001_mesh_layer_1_vtx_0[8];
extern Gfx jrb_dl_Ground_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Ground_001_mesh_layer_4_vtx_cull[8];
extern Vtx jrb_dl_Ground_001_mesh_layer_4_vtx_0[12];
extern Gfx jrb_dl_Ground_001_mesh_layer_4_tri_0[];
extern Vtx jrb_dl_DogHouseExterior_003_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_DogHouseExterior_003_mesh_layer_1_vtx_0[102];
extern Gfx jrb_dl_DogHouseExterior_003_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_DogHouseExterior_003_mesh_layer_1_vtx_1[4];
extern Gfx jrb_dl_DogHouseExterior_003_mesh_layer_1_tri_1[];
extern Vtx jrb_dl_Grass_mesh_layer_4_vtx_0[28];
extern Gfx jrb_dl_Grass_mesh_layer_4_tri_0[];
extern Vtx jrb_dl_Ground_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Ground_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Moon_mesh_layer_4_vtx_0[16];
extern Gfx jrb_dl_Moon_mesh_layer_4_tri_0[];
extern Vtx jrb_dl_Skybox_mesh_layer_1_vtx_0[524];
extern Gfx jrb_dl_Skybox_mesh_layer_1_tri_0[];
extern Gfx mat_jrb_dl_Wood[];
extern Gfx mat_revert_jrb_dl_Wood[];
extern Gfx mat_jrb_dl_Roof[];
extern Gfx mat_revert_jrb_dl_Roof[];
extern Gfx mat_jrb_dl_Black[];
extern Gfx mat_jrb_dl_Grass[];
extern Gfx mat_revert_jrb_dl_Grass[];
extern Gfx mat_jrb_dl_Fence[];
extern Gfx mat_revert_jrb_dl_Fence[];
extern Gfx mat_jrb_dl_ForestWall[];
extern Gfx mat_revert_jrb_dl_ForestWall[];
extern Gfx mat_jrb_dl_Moon[];
extern Gfx mat_jrb_dl_Skybox[];
extern Gfx jrb_dl_DogHouseExterior_mesh_layer_1[];
extern Gfx jrb_dl_DogHouseExterior_001_mesh_layer_1[];
extern Gfx jrb_dl_Ground_001_mesh_layer_1[];
extern Gfx jrb_dl_Ground_001_mesh_layer_4[];
extern Gfx jrb_dl_DogHouseExterior_003_mesh_layer_1[];
extern Gfx jrb_dl_Grass_mesh_layer_4[];
extern Gfx jrb_dl_Ground_mesh_layer_1[];
extern Gfx jrb_dl_Moon_mesh_layer_4[];
extern Gfx jrb_dl_Skybox_mesh_layer_1[];
extern Gfx jrb_dl_material_revert_render_settings[];
