extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_dl_101__Garden_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const u8 jrb_area_1_collision_rooms[];
extern const MacroObject jrb_area_1_macro_objs[];
extern const GeoLayout jrb_area_2_geo[];
extern const GeoLayout jrb_dl_201__Fall_geo[];
extern const GeoLayout jrb_area_2[];
extern const Collision jrb_area_2_collision[];
extern const u8 jrb_area_2_collision_rooms[];
extern const MacroObject jrb_area_2_macro_objs[];
extern u8 jrb_dl_dark_grass2_ci4[];
extern u8 jrb_dl_dark_grass2_ci4_pal_rgba16[];
extern u8 jrb_dl_forest_wall_ci4[];
extern u8 jrb_dl_forest_wall_ci4_pal_rgba16[];
extern u8 jrb_dl_moon_rgba16[];
extern u8 jrb_dl_night_skybox3_rgba16[];
extern Vtx jrb_dl_Ground_001_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Ground_001_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Ground_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Grass_mesh_layer_4_vtx_0[28];
extern Gfx jrb_dl_Grass_mesh_layer_4_tri_0[];
extern Vtx jrb_dl_Ground_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Ground_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Moon_mesh_layer_4_vtx_0[16];
extern Gfx jrb_dl_Moon_mesh_layer_4_tri_0[];
extern Vtx jrb_dl_Skybox_mesh_layer_1_vtx_0[524];
extern Gfx jrb_dl_Skybox_mesh_layer_1_tri_0[];
extern Gfx mat_jrb_dl_Grass[];
extern Gfx mat_revert_jrb_dl_Grass[];
extern Gfx mat_jrb_dl_ForestWall[];
extern Gfx mat_revert_jrb_dl_ForestWall[];
extern Gfx mat_jrb_dl_Moon[];
extern Gfx mat_jrb_dl_Skybox[];
extern Gfx jrb_dl_Ground_001_mesh_layer_1[];
extern Gfx jrb_dl_Grass_mesh_layer_4[];
extern Gfx jrb_dl_Ground_mesh_layer_1[];
extern Gfx jrb_dl_Moon_mesh_layer_4[];
extern Gfx jrb_dl_Skybox_mesh_layer_1[];
extern Gfx jrb_dl_material_revert_render_settings[];
