extern const GeoLayout mirror_geo[];
extern Lights1 mirror_Mirror_Edge_001_lights;
extern u8 mirror_mirror_edge_i8[];
extern u8 mirror_mirror2_ci8[];
extern u8 mirror_mirror2_ci8_pal_rgba16[];
extern Vtx mirror_Mirror_001_mesh_layer_1_vtx_0[50];
extern Gfx mirror_Mirror_001_mesh_layer_1_tri_0[];
extern Vtx mirror_Mirror_001_mesh_layer_1_vtx_1[6];
extern Gfx mirror_Mirror_001_mesh_layer_1_tri_1[];
extern Gfx mat_mirror_Mirror_Edge_001[];
extern Gfx mat_revert_mirror_Mirror_Edge_001[];
extern Gfx mat_mirror_Mirror_002[];
extern Gfx mat_revert_mirror_Mirror_002[];
extern Gfx mirror_Mirror_001_mesh_layer_1[];
extern Gfx mirror_material_revert_render_settings[];
