extern const GeoLayout bg_ground_center_geo[];
extern u8 bg_ground_center_BOOGOO1_i4[];
extern u8 bg_ground_center_BOOGOO2_i4[];
extern Vtx bg_ground_center_BGGroundCenter_mesh_layer_1_vtx_cull[8];
extern Vtx bg_ground_center_BGGroundCenter_mesh_layer_1_vtx_0[32];
extern Gfx bg_ground_center_BGGroundCenter_mesh_layer_1_tri_0[];
extern Gfx mat_bg_ground_center_BooGooObj_layer1[];
extern Gfx mat_revert_bg_ground_center_BooGooObj_layer1[];
extern Gfx bg_ground_center_BGGroundCenter_mesh_layer_1[];
extern Gfx bg_ground_center_material_revert_render_settings[];
