extern const GeoLayout floating_plant_geo[];
extern Lights1 floating_plant_BigVine_lights;
extern Lights1 floating_plant_Leaf_002_lights;
extern u8 floating_plant_plantvine_ci8[];
extern u8 floating_plant_plantvine_ci8_pal_rgba16[];
extern u8 floating_plant_K_leaf_ci8[];
extern u8 floating_plant_K_leaf_ci8_pal_rgba16[];
extern Vtx floating_plant_FloatingPlant_mesh_layer_1_vtx_cull[8];
extern Vtx floating_plant_FloatingPlant_mesh_layer_1_vtx_0[32];
extern Gfx floating_plant_FloatingPlant_mesh_layer_1_tri_0[];
extern Vtx floating_plant_FloatingPlant_mesh_layer_1_vtx_1[76];
extern Gfx floating_plant_FloatingPlant_mesh_layer_1_tri_1[];
extern Gfx mat_floating_plant_BigVine[];
extern Gfx mat_revert_floating_plant_BigVine[];
extern Gfx mat_floating_plant_Leaf_002[];
extern Gfx mat_revert_floating_plant_Leaf_002[];
extern Gfx floating_plant_FloatingPlant_mesh_layer_1[];
extern Gfx floating_plant_material_revert_render_settings[];
