extern const GeoLayout block_tower_geo[];
extern Lights1 block_tower_Jenga_002_lights;
extern u8 block_tower_living_wood2_ci8[];
extern u8 block_tower_living_wood2_ci8_pal_rgba16[];
extern Vtx block_tower_JengaTower_mesh_layer_1_vtx_cull[8];
extern Vtx block_tower_JengaTower_mesh_layer_1_vtx_0[600];
extern Gfx block_tower_JengaTower_mesh_layer_1_tri_0[];
extern Gfx mat_block_tower_Jenga_002[];
extern Gfx mat_revert_block_tower_Jenga_002[];
extern Gfx block_tower_JengaTower_mesh_layer_1[];
extern Gfx block_tower_material_revert_render_settings[];
