#include "levels/ddd/hole_wall_ground/texscroll.inc.h"
#include "levels/ddd/texscroll.inc.h"
#include "levels/ddd/hole_wall/texscroll.inc.h"
#include "levels/ddd/end_laser/texscroll.inc.h"
#include "levels/ddd/end_spike/texscroll.inc.h"
#include "levels/ddd/end_log/texscroll.inc.h"
#include "levels/ddd/end_bubble/texscroll.inc.h"
#include "levels/ddd/end_fist/texscroll.inc.h"
#include "levels/ddd/end_cage/texscroll.inc.h"
#include "levels/ddd/end_boo/texscroll.inc.h"
#include "levels/ddd/end_shyguy/texscroll.inc.h"
#include "levels/ddd/end_goomba/texscroll.inc.h"
#include "levels/ddd/controller/texscroll.inc.h"
extern void scroll_textures_ddd();
