#include "levels/hmc/attic_spire/texscroll.inc.h"
#include "levels/hmc/foreroom_object/texscroll.inc.h"
#include "levels/hmc/sauna_rock_rise/texscroll.inc.h"
#include "levels/hmc/vase_throw/texscroll.inc.h"
#include "levels/hmc/static_wall/texscroll.inc.h"
#include "levels/hmc/trophy_rectangle/texscroll.inc.h"
#include "levels/hmc/trophy_octogon/texscroll.inc.h"
#include "levels/hmc/pool_floor/texscroll.inc.h"
#include "levels/hmc/pool_barrier/texscroll.inc.h"
#include "levels/hmc/texscroll.inc.h"
extern void scroll_textures_hmc();
