#include "levels/lll/wall_hammerbro/texscroll.inc.h"
#include "levels/lll/wall_goomba/texscroll.inc.h"
#include "levels/lll/power_bar/texscroll.inc.h"
#include "levels/lll/power_button/texscroll.inc.h"
#include "levels/lll/power_plat/texscroll.inc.h"
#include "levels/lll/big_swinging_plat/texscroll.inc.h"
#include "levels/lll/sawblade/texscroll.inc.h"
#include "levels/lll/swinging_plat/texscroll.inc.h"
#include "levels/lll/power_door/texscroll.inc.h"
#include "levels/lll/dust_bunny/texscroll.inc.h"
#include "levels/lll/clothes_ball/texscroll.inc.h"
#include "levels/lll/texscroll.inc.h"
extern void scroll_textures_lll();
