#include "levels/ssl/mind_mips/texscroll.inc.h"
#include "levels/ssl/mind_mound/texscroll.inc.h"
#include "levels/ssl/o1_bg/texscroll.inc.h"
#include "levels/ssl/lab_bg/texscroll.inc.h"
#include "levels/ssl/big_spinning_plat/texscroll.inc.h"
#include "levels/ssl/spinning_plat/texscroll.inc.h"
#include "levels/ssl/texscroll.inc.h"
#include "levels/ssl/o2_boogoo/texscroll.inc.h"
#include "levels/ssl/bg_asteroid/texscroll.inc.h"
#include "levels/ssl/ag_boogoo/texscroll.inc.h"
#include "levels/ssl/cage_goo/texscroll.inc.h"
#include "levels/ssl/boogoo_shyguy/texscroll.inc.h"
#include "levels/ssl/boogoo_koopa/texscroll.inc.h"
#include "levels/ssl/boogoo_goomba/texscroll.inc.h"
extern void scroll_textures_ssl();
