extern const GeoLayout attic_rock_geo[];
extern Lights1 attic_rock_SaunaPlat_003_layer1_lights;
extern u8 attic_rock_dirty_wood_grey3_i8[];
extern u8 attic_rock_ci4_cracked_rocks_i4[];
extern u8 attic_rock_MetalGround_i8[];
extern Vtx attic_rock_AtticRockSpike_mesh_layer_1_vtx_cull[8];
extern Vtx attic_rock_AtticRockSpike_mesh_layer_1_vtx_0[21];
extern Gfx attic_rock_AtticRockSpike_mesh_layer_1_tri_0[];
extern Vtx attic_rock_AtticRockSpike_mesh_layer_1_vtx_1[108];
extern Gfx attic_rock_AtticRockSpike_mesh_layer_1_tri_1[];
extern Gfx mat_attic_rock_SaunaPlat_003_layer1[];
extern Gfx mat_revert_attic_rock_SaunaPlat_003_layer1[];
extern Gfx mat_attic_rock_MetalSpikes[];
extern Gfx mat_revert_attic_rock_MetalSpikes[];
extern Gfx attic_rock_AtticRockSpike_mesh_layer_1[];
extern Gfx attic_rock_material_revert_render_settings[];
