extern const GeoLayout sand_crab_geo[];
extern u8 sand_crab_ci4_mound_indicator_ci4[];
extern u8 sand_crab_ci4_mound_indicator_ci4_pal_rgba16[];
extern Vtx sand_crab_crabsign_mesh_layer_1_vtx_cull[8];
extern Vtx sand_crab_crabsign_mesh_layer_1_vtx_0[28];
extern Gfx sand_crab_crabsign_mesh_layer_1_tri_0[];
extern Gfx mat_sand_crab_CrabSign[];
extern Gfx mat_revert_sand_crab_CrabSign[];
extern Gfx sand_crab_crabsign_mesh_layer_1[];
extern Gfx sand_crab_material_revert_render_settings[];
