#include "src/game/envfx_snow.h"

const GeoLayout shower_wall_ShowerWallIn[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, shower_wall_start_showerIn_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout shower_wall_switch_opt1_jump_shower_wall_ShowerWallIn[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shower_wall_start_showerIn_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout shower_wall_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_shower),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shower_wall_shower_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, shower_wall_switch_opt1_jump_shower_wall_ShowerWallIn),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout shower_wall_geo[] = {
	GEO_CULLING_RADIUS(4096),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_update_layer_transparency_and_color),
			GEO_SWITCH_CASE(2, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_SWITCH_CASE(2, geo_switch_shower),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, shower_wall_shower_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_BRANCH(1, shower_wall_ShowerWallIn),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, shower_wall_switch_opt1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, shower_wall_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, shower_wall_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
