extern const GeoLayout trophy_elevator_geo[];
extern u8 trophy_elevator_deepplanks_redbrown_rgba16[];
extern u8 trophy_elevator_i4_matt_multitex_i4[];
extern Vtx trophy_elevator_TrophyElevator_mesh_layer_1_vtx_cull[8];
extern Vtx trophy_elevator_TrophyElevator_mesh_layer_1_vtx_0[8];
extern Gfx trophy_elevator_TrophyElevator_mesh_layer_1_tri_0[];
extern Gfx mat_trophy_elevator_WoodFloorTrophyRoom_002_layer1[];
extern Gfx mat_revert_trophy_elevator_WoodFloorTrophyRoom_002_layer1[];
extern Gfx trophy_elevator_TrophyElevator_mesh_layer_1[];
extern Gfx trophy_elevator_material_revert_render_settings[];
