#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/bbh/header.h"

#include "levels/bbh/staircase_step/geo.inc.c"
#include "levels/bbh/tilting_trap_platform/geo.inc.c"
#include "levels/bbh/tumbling_platform_far/geo.inc.c"
#include "levels/bbh/tumbling_platform_near/geo.inc.c"
#include "levels/bbh/moving_bookshelf/geo.inc.c"
#include "levels/bbh/mesh_elevator/geo.inc.c"
#include "levels/bbh/merry_go_round/geo.inc.c"
#include "levels/bbh/coffin/geo.inc.c"
#include "levels/bbh/areas/1/geo.inc.c"
#include "levels/bbh/geo.inc.c"

#include "levels/bbh/fake_dirt_wall/geo.inc.c"
#include "levels/bbh/bomb_rock/geo.inc.c"
#include "levels/bbh/unstable_rock/geo.inc.c"
#include "levels/bbh/snowflake/geo.inc.c"
#include "levels/bbh/unstable_rock_yellow/geo.inc.c"
#include "levels/bbh/stalactite/geo.inc.c"
#include "levels/bbh/sand_mound/geo.inc.c"
#include "levels/bbh/sand_crab/geo.inc.c"
#include "levels/bbh/snow_box/geo.inc.c"
#include "levels/bbh/snow_pile/geo.inc.c"
#include "levels/bbh/ice_cube/geo.inc.c"
#include "levels/bbh/ice_cube_cracked/geo.inc.c"
#include "levels/bbh/ice_cube_chunk/geo.inc.c"
#include "levels/bbh/bomb_chain/geo.inc.c"
#include "levels/bbh/big_ice_cube/geo.inc.c"
#include "levels/bbh/red_button/geo.inc.c"
#include "levels/bbh/ice_ceiling_gate/geo.inc.c"
#include "levels/bbh/rubberband_two/geo.inc.c"