extern const GeoLayout bbh_area_1_geo[];
extern const GeoLayout bbh_dl_101__Oasis_geo[];
extern const GeoLayout bbh_area_1[];
extern const Collision bbh_area_1_collision[];
extern const u8 bbh_area_1_collision_rooms[];
extern const MacroObject bbh_area_1_macro_objs[];
extern Lights1 bbh_dl_Sand_lights;
extern Lights1 bbh_dl_Grass_lights;
extern Lights1 bbh_dl_GrassToSand_layer1_lights;
extern Lights1 bbh_dl_GrassEdge_layer1_lights;
extern Lights1 bbh_dl_DirtWall_lights;
extern Lights1 bbh_dl_Water_lights;
extern u8 bbh_dl_grayscale_sand_i8[];
extern u8 bbh_dl_i8_grass_i8[];
extern u8 bbh_dl_i8_grass_i4[];
extern u8 bbh_dl_grayscale_sand_i4[];
extern u8 bbh_dl_dirtwall_rgba16[];
extern u8 bbh_dl_grass_edge_rgba16[];
extern u8 bbh_dl_dirtwall_ci8[];
extern u8 bbh_dl_dirtwall_ci8_pal_rgba16[];
extern u8 bbh_dl_water_ci8[];
extern u8 bbh_dl_water_ci8_pal_rgba16[];
extern Vtx bbh_dl_Grass_mesh_layer_1_vtx_cull[8];
extern Vtx bbh_dl_Grass_mesh_layer_1_vtx_0[24];
extern Gfx bbh_dl_Grass_mesh_layer_1_tri_0[];
extern Vtx bbh_dl_Grass_mesh_layer_1_vtx_1[32];
extern Gfx bbh_dl_Grass_mesh_layer_1_tri_1[];
extern Vtx bbh_dl_Grass_mesh_layer_1_vtx_2[16];
extern Gfx bbh_dl_Grass_mesh_layer_1_tri_2[];
extern Vtx bbh_dl_Grass_mesh_layer_1_vtx_3[26];
extern Gfx bbh_dl_Grass_mesh_layer_1_tri_3[];
extern Vtx bbh_dl_Grass_mesh_layer_1_vtx_4[54];
extern Gfx bbh_dl_Grass_mesh_layer_1_tri_4[];
extern Vtx bbh_dl_Water_mesh_layer_5_vtx_cull[8];
extern Vtx bbh_dl_Water_mesh_layer_5_vtx_0[9];
extern Gfx bbh_dl_Water_mesh_layer_5_tri_0[];
extern Gfx mat_bbh_dl_Sand[];
extern Gfx mat_revert_bbh_dl_Sand[];
extern Gfx mat_bbh_dl_Grass[];
extern Gfx mat_revert_bbh_dl_Grass[];
extern Gfx mat_bbh_dl_GrassToSand_layer1[];
extern Gfx mat_revert_bbh_dl_GrassToSand_layer1[];
extern Gfx mat_bbh_dl_GrassEdge_layer1[];
extern Gfx mat_revert_bbh_dl_GrassEdge_layer1[];
extern Gfx mat_bbh_dl_DirtWall[];
extern Gfx mat_revert_bbh_dl_DirtWall[];
extern Gfx mat_bbh_dl_Water[];
extern Gfx mat_revert_bbh_dl_Water[];
extern Gfx bbh_dl_Grass_mesh_layer_1[];
extern Gfx bbh_dl_Water_mesh_layer_5[];
extern Gfx bbh_dl_material_revert_render_settings[];
