extern const GeoLayout opening_wall_switch_opt1[];
extern const GeoLayout opening_wall_geo[];
extern u8 opening_wall_shortbluewall_rgba16[];
extern u8 opening_wall_cracked_multitex_i4[];
extern Vtx opening_wall_openingwall_mesh_layer_5_vtx_0[4];
extern Gfx opening_wall_openingwall_mesh_layer_5_tri_0[];
extern Gfx mat_opening_wall_WallOpacity_layer5[];
extern Gfx mat_revert_opening_wall_WallOpacity_layer5[];
extern Gfx opening_wall_openingwall_mesh_layer_5[];
extern Gfx opening_wall_material_revert_render_settings[];
