extern const GeoLayout new_shyguy_000_switchcase_opt1[];
extern const GeoLayout new_shyguy_geo[];
extern Lights1 new_shyguy_Shyguy1_002_lights;
extern Lights1 new_shyguy_Shyguy2_002_lights;
extern u8 new_shyguy_shyguy1_black_i8[];
extern u8 new_shyguy_shyguy2_ci8[];
extern u8 new_shyguy_shyguy2_ci8_pal_rgba16[];
extern Vtx new_shyguy_shyguy_mesh_layer_1_vtx_0[9];
extern Gfx new_shyguy_shyguy_mesh_layer_1_tri_0[];
extern Vtx new_shyguy_shyguy_mesh_layer_1_vtx_1[68];
extern Gfx new_shyguy_shyguy_mesh_layer_1_tri_1[];
extern Vtx new_shyguy_shyguy_mesh_layer_1_vtx_2[49];
extern Gfx new_shyguy_shyguy_mesh_layer_1_tri_2[];
extern Gfx mat_new_shyguy_Shyguy1_002[];
extern Gfx mat_new_shyguy_Shyguy2_002[];
extern Gfx mat_revert_new_shyguy_Shyguy2_002[];
extern Gfx mat_new_shyguy_Black[];
extern Gfx new_shyguy_shyguy_mesh_layer_1[];
extern Gfx new_shyguy_material_revert_render_settings[];
