extern const GeoLayout bomb_rock_geo[];
extern Lights1 bomb_rock_Rock_001_layer1_lights;
extern u8 bomb_rock_rocks_rgba16[];
extern u8 bomb_rock_i4_cracks3_i4[];
extern Vtx bomb_rock_ROCK_mesh_layer_1_vtx_cull[8];
extern Vtx bomb_rock_ROCK_mesh_layer_1_vtx_0[24];
extern Gfx bomb_rock_ROCK_mesh_layer_1_tri_0[];
extern Gfx mat_bomb_rock_Rock_001_layer1[];
extern Gfx mat_revert_bomb_rock_Rock_001_layer1[];
extern Gfx bomb_rock_ROCK_mesh_layer_1[];
extern Gfx bomb_rock_material_revert_render_settings[];
