extern const GeoLayout printer_geo[];
extern u8 printer_rovertsquish_ia8[];
extern Vtx printer_Printer_mesh_layer_1_vtx_cull[8];
extern Vtx printer_Printer_mesh_layer_1_vtx_0[39];
extern Gfx printer_Printer_mesh_layer_1_tri_0[];
extern Vtx printer_Printer_mesh_layer_1_vtx_1[40];
extern Gfx printer_Printer_mesh_layer_1_tri_1[];
extern Gfx mat_printer_VertexColored_002[];
extern Gfx mat_revert_printer_VertexColored_002[];
extern Gfx mat_printer_Marker_002[];
extern Gfx printer_Printer_mesh_layer_1[];
extern Gfx printer_material_revert_render_settings[];
