extern const GeoLayout mem_fall_floor_geo[];
extern u8 mem_fall_floor_RockPattern09_ci8[];
extern u8 mem_fall_floor_RockPattern09_ci8_pal_rgba16[];
extern u8 mem_fall_floor_stonetiles_i8[];
extern Vtx mem_fall_floor_FallingFloor_mesh_layer_1_vtx_0[32];
extern Gfx mem_fall_floor_FallingFloor_mesh_layer_1_tri_0[];
extern Vtx mem_fall_floor_FallingFloor_mesh_layer_1_vtx_1[8];
extern Gfx mem_fall_floor_FallingFloor_mesh_layer_1_tri_1[];
extern Gfx mat_mem_fall_floor_Ground_006[];
extern Gfx mat_revert_mem_fall_floor_Ground_006[];
extern Gfx mat_mem_fall_floor_BathroomTiles_002[];
extern Gfx mat_revert_mem_fall_floor_BathroomTiles_002[];
extern Gfx mem_fall_floor_FallingFloor_mesh_layer_1[];
extern Gfx mem_fall_floor_material_revert_render_settings[];
