extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_dl_101__The_Corridor_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const u8 lll_area_1_collision_rooms[];
extern const MacroObject lll_area_1_macro_objs[];
extern u8 lll_dl_garage_floor2_i8[];
extern u8 lll_dl_wallpaper_32x_rgba16[];
extern u8 lll_dl_i8_garage_wall_i4[];
extern Vtx lll_dl_Corridor_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Corridor_mesh_layer_1_vtx_0[4];
extern Gfx lll_dl_Corridor_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Corridor_mesh_layer_1_vtx_1[10];
extern Gfx lll_dl_Corridor_mesh_layer_1_tri_1[];
extern Gfx mat_lll_dl_CorridorFloor[];
extern Gfx mat_revert_lll_dl_CorridorFloor[];
extern Gfx mat_lll_dl_CorridorWall_layer1[];
extern Gfx mat_revert_lll_dl_CorridorWall_layer1[];
extern Gfx lll_dl_Corridor_mesh_layer_1[];
extern Gfx lll_dl_material_revert_render_settings[];
