extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_dl_101__The_Corridor_geo[];
extern const GeoLayout lll_dl_102__Laundry_Room_geo[];
extern const GeoLayout lll_dl_103__Gym_geo[];
extern const GeoLayout lll_dl_104__Wine_Cellar_geo[];
extern const GeoLayout lll_dl_105__Root_Cellar_geo[];
extern const GeoLayout lll_dl_106__Meat_Locker_geo[];
extern const GeoLayout lll_dl_107__Engine_Room_geo[];
extern const GeoLayout lll_dl_108__Torture_Chamber_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const u8 lll_area_1_collision_rooms[];
extern const MacroObject lll_area_1_macro_objs[];
extern u8 lll_dl_garage_floor2_i8[];
extern u8 lll_dl_wallpaper_32x_rgba16[];
extern u8 lll_dl_i8_garage_wall_i4[];
extern u8 lll_dl_i4_spiderweb_i4[];
extern u8 lll_dl_march_wood3_ci8[];
extern u8 lll_dl_march_wood3_ci8_pal_rgba16[];
extern u8 lll_dl_bright_cloud_i4[];
extern u8 lll_dl_cloud_alphamap_i4[];
extern Vtx lll_dl_BasementStairs_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_BasementStairs_mesh_layer_1_vtx_0[32];
extern Gfx lll_dl_BasementStairs_mesh_layer_1_tri_0[];
extern Vtx lll_dl_BasementStairs_mesh_layer_1_vtx_1[64];
extern Gfx lll_dl_BasementStairs_mesh_layer_1_tri_1[];
extern Vtx lll_dl_Cobwebs_mesh_layer_4_vtx_0[16];
extern Gfx lll_dl_Cobwebs_mesh_layer_4_tri_0[];
extern Vtx lll_dl_Corridor_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Corridor_mesh_layer_1_vtx_0[52];
extern Gfx lll_dl_Corridor_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Corridor_mesh_layer_1_vtx_1[152];
extern Gfx lll_dl_Corridor_mesh_layer_1_tri_1[];
extern Vtx lll_dl_Corridor_mesh_layer_1_vtx_2[239];
extern Gfx lll_dl_Corridor_mesh_layer_1_tri_2[];
extern Vtx lll_dl_Fog_mesh_layer_5_vtx_cull[8];
extern Vtx lll_dl_Fog_mesh_layer_5_vtx_0[18];
extern Gfx lll_dl_Fog_mesh_layer_5_tri_0[];
extern Vtx lll_dl_LaundryRoom_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_LaundryRoom_mesh_layer_1_vtx_0[31];
extern Gfx lll_dl_LaundryRoom_mesh_layer_1_tri_0[];
extern Vtx lll_dl_LaundryRoom_mesh_layer_1_vtx_1[8];
extern Gfx lll_dl_LaundryRoom_mesh_layer_1_tri_1[];
extern Vtx lll_dl_Gym_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Gym_mesh_layer_1_vtx_0[28];
extern Gfx lll_dl_Gym_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Gym_mesh_layer_1_vtx_1[8];
extern Gfx lll_dl_Gym_mesh_layer_1_tri_1[];
extern Vtx lll_dl_WineCellar_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_WineCellar_mesh_layer_1_vtx_0[73];
extern Gfx lll_dl_WineCellar_mesh_layer_1_tri_0[];
extern Vtx lll_dl_WineCellar_mesh_layer_1_vtx_1[12];
extern Gfx lll_dl_WineCellar_mesh_layer_1_tri_1[];
extern Vtx lll_dl_RootCellar_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_RootCellar_mesh_layer_1_vtx_0[78];
extern Gfx lll_dl_RootCellar_mesh_layer_1_tri_0[];
extern Vtx lll_dl_RootCellar_mesh_layer_1_vtx_1[12];
extern Gfx lll_dl_RootCellar_mesh_layer_1_tri_1[];
extern Vtx lll_dl_Meat_Locker_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Meat_Locker_mesh_layer_1_vtx_0[31];
extern Gfx lll_dl_Meat_Locker_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Meat_Locker_mesh_layer_1_vtx_1[8];
extern Gfx lll_dl_Meat_Locker_mesh_layer_1_tri_1[];
extern Vtx lll_dl_EngineRoom_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_EngineRoom_mesh_layer_1_vtx_0[31];
extern Gfx lll_dl_EngineRoom_mesh_layer_1_tri_0[];
extern Vtx lll_dl_EngineRoom_mesh_layer_1_vtx_1[8];
extern Gfx lll_dl_EngineRoom_mesh_layer_1_tri_1[];
extern Vtx lll_dl_TortureChamber_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_TortureChamber_mesh_layer_1_vtx_0[28];
extern Gfx lll_dl_TortureChamber_mesh_layer_1_tri_0[];
extern Vtx lll_dl_TortureChamber_mesh_layer_1_vtx_1[8];
extern Gfx lll_dl_TortureChamber_mesh_layer_1_tri_1[];
extern Gfx mat_lll_dl_CorridorFloor[];
extern Gfx mat_revert_lll_dl_CorridorFloor[];
extern Gfx mat_lll_dl_CorridorWall_layer1[];
extern Gfx mat_revert_lll_dl_CorridorWall_layer1[];
extern Gfx mat_lll_dl_Cobweb[];
extern Gfx mat_revert_lll_dl_Cobweb[];
extern Gfx mat_lll_dl_WoodBeams[];
extern Gfx mat_revert_lll_dl_WoodBeams[];
extern Gfx mat_lll_dl_Fog_layer5[];
extern Gfx mat_revert_lll_dl_Fog_layer5[];
extern Gfx lll_dl_BasementStairs_mesh_layer_1[];
extern Gfx lll_dl_Cobwebs_mesh_layer_4[];
extern Gfx lll_dl_Corridor_mesh_layer_1[];
extern Gfx lll_dl_Fog_mesh_layer_5[];
extern Gfx lll_dl_LaundryRoom_mesh_layer_1[];
extern Gfx lll_dl_Gym_mesh_layer_1[];
extern Gfx lll_dl_WineCellar_mesh_layer_1[];
extern Gfx lll_dl_RootCellar_mesh_layer_1[];
extern Gfx lll_dl_Meat_Locker_mesh_layer_1[];
extern Gfx lll_dl_EngineRoom_mesh_layer_1[];
extern Gfx lll_dl_TortureChamber_mesh_layer_1[];
extern Gfx lll_dl_material_revert_render_settings[];
