extern const GeoLayout end_fist_geo[];
extern u8 end_fist_BOOGOO1_i4[];
extern u8 end_fist_BOOGOO2_i4[];
extern Vtx end_fist_Fist_mesh_layer_1_vtx_cull[8];
extern Vtx end_fist_Fist_mesh_layer_1_vtx_0[32];
extern Gfx end_fist_Fist_mesh_layer_1_tri_0[];
extern Gfx mat_end_fist_BooGooObj_layer1[];
extern Gfx mat_revert_end_fist_BooGooObj_layer1[];
extern Gfx end_fist_Fist_mesh_layer_1[];
extern Gfx end_fist_material_revert_render_settings[];
