#include "levels/thi/area_1/collision.inc.c"
#include "levels/thi/area_1/room.inc.c"
#include "levels/thi/area_1/macro.inc.c"
#include "levels/thi/area_1/spline.inc.c"
#include "levels/thi/model.inc.c"
