extern const GeoLayout toy_mole_geo[];
extern Lights1 toy_mole_Mole_lights;
extern Lights1 toy_mole_Top_lights;
extern u8 toy_mole_toymontymole_rgba16[];
extern u8 toy_mole_i4_marker_i8[];
extern Vtx toy_mole_Mole_mesh_layer_1_vtx_cull[8];
extern Vtx toy_mole_Mole_mesh_layer_1_vtx_0[27];
extern Gfx toy_mole_Mole_mesh_layer_1_tri_0[];
extern Vtx toy_mole_Mole_mesh_layer_1_vtx_1[9];
extern Gfx toy_mole_Mole_mesh_layer_1_tri_1[];
extern Gfx mat_toy_mole_Mole[];
extern Gfx mat_revert_toy_mole_Mole[];
extern Gfx mat_toy_mole_Top[];
extern Gfx mat_revert_toy_mole_Top[];
extern Gfx toy_mole_Mole_mesh_layer_1[];
extern Gfx toy_mole_material_revert_render_settings[];
