#include "src/game/envfx_snow.h"

const GeoLayout wdw_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, wdw_dl_101__Main_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout wdw_dl_101__Main_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wdw_dl_MainHall_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, wdw_dl_MainHall_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wdw_dl_Hallway_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wdw_dl_Truck_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wdw_dl_MRoomCrate_007_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wdw_dl_Plate_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wdw_dl_TV_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wdw_dl_GBook_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wdw_dl_HalfPillar_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wdw_dl_Light_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wdw_dl_Study_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wdw_dl_Checkered_Goal_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout wdw_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_L8_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, wdw_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wdw_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, wdw_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
