#include "src/game/envfx_snow.h"

const GeoLayout blue_owl_geo[] = {
	GEO_CULLING_RADIUS(4096),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 255, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 147, -5, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, blue_owl_000_offset_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 96, 0, 0, blue_owl_000_offset_002_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 34, -35, 31, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, blue_owl_000_offset_003_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 91, 0, 0, blue_owl_000_offset_004_mesh_layer_4),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 121, 0, 0, blue_owl_000_offset_005_mesh_layer_4),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 121, 0, 0, NULL),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 91, 0, 0, NULL),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, blue_owl_002_offset_001_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -31, 5, 37, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, blue_owl_000_offset_006_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 0, blue_owl_000_offset_007_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -31, 5, -37, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, blue_owl_000_offset_008_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 0, blue_owl_000_offset_009_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 34, -35, -31, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, blue_owl_000_offset_010_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 91, 0, 0, blue_owl_000_offset_011_mesh_layer_4),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 121, 0, 0, blue_owl_000_offset_012_mesh_layer_4),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 121, 0, 0, NULL),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 91, 0, 0, NULL),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, blue_owl_002_offset_003_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, blue_owl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, blue_owl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
