#include "src/game/envfx_snow.h"

const GeoLayout end_spike_geo[] = {
	GEO_CULLING_RADIUS(4096),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 27, 0, end_spike_SpikeBody_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, end_spike_SpikeLArm_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 50, 53, -7, end_spike_SpikeLArm_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, end_spike_SpikeLLeg_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 25, -27, -13, end_spike_SpikeLLeg_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, end_spike_SpikeRArm_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -50, 53, -7, end_spike_SpikeRArm_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, end_spike_SpikeRLeg_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -25, -27, -11, end_spike_SpikeRLeg_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 171, 25, NULL),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_update_spike_log),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, end_spike_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
