#include "anim_ascend.inc.c"
#include "anim_moving.inc.c"
#include "anim_throw_book.inc.c"
#include "anim_throw_flame.inc.c"
#include "anim_lose_helmet.inc.c"
#include "anim_hit.inc.c"
#include "anim_death.inc.c"
