extern const GeoLayout gravity_sign_switch_opt1[];
extern const GeoLayout gravity_sign_geo[];
extern u8 gravity_sign_garage_floor2_i8[];
extern u8 gravity_sign_i4_matt_multitex_i4[];
extern u8 gravity_sign_gravity_ci4[];
extern u8 gravity_sign_gravity_ci4_pal_rgba16[];
extern u8 gravity_sign_normal_ia8[];
extern u8 gravity_sign_low_ia8[];
extern Vtx gravity_sign_gravSign_mesh_layer_1_vtx_0[8];
extern Gfx gravity_sign_gravSign_mesh_layer_1_tri_0[];
extern Vtx gravity_sign_gravSign_mesh_layer_6_vtx_0[4];
extern Gfx gravity_sign_gravSign_mesh_layer_6_tri_0[];
extern Vtx gravity_sign_gravSign_mesh_layer_6_vtx_1[4];
extern Gfx gravity_sign_gravSign_mesh_layer_6_tri_1[];
extern Gfx mat_gravity_sign_CorridorFloor_layer1[];
extern Gfx mat_revert_gravity_sign_CorridorFloor_layer1[];
extern Gfx mat_gravity_sign_Gravity[];
extern Gfx mat_revert_gravity_sign_Gravity[];
extern Gfx mat_gravity_sign_Normal[];
extern Gfx mat_revert_gravity_sign_Normal[];
extern Gfx mat_gravity_sign_Low[];
extern Gfx mat_revert_gravity_sign_Low[];
extern Gfx gravity_sign_gravSign_mesh_layer_1[];
extern Gfx gravity_sign_gravSign_mesh_layer_1_mat_override_Low_0[];
extern Gfx gravity_sign_gravSign_mesh_layer_6[];
extern Gfx gravity_sign_gravSign_mesh_layer_6_mat_override_Low_0[];
extern Gfx gravity_sign_material_revert_render_settings[];
