extern const GeoLayout blocker_entertainment_geo[];
extern u8 blocker_entertainment_shortbluewall_rgba16[];
extern Vtx blocker_entertainment_BlockerEntertainment_mesh_layer_1_vtx_cull[8];
extern Vtx blocker_entertainment_BlockerEntertainment_mesh_layer_1_vtx_0[4];
extern Gfx blocker_entertainment_BlockerEntertainment_mesh_layer_1_tri_0[];
extern Gfx mat_blocker_entertainment_Wall_002[];
extern Gfx mat_revert_blocker_entertainment_Wall_002[];
extern Gfx blocker_entertainment_BlockerEntertainment_mesh_layer_1[];
extern Gfx blocker_entertainment_material_revert_render_settings[];
