extern const GeoLayout bouncy_bed_geo[];
extern u8 bouncy_bed_whitesheets_ci4[];
extern u8 bouncy_bed_whitesheets_ci4_pal_rgba16[];
extern u8 bouncy_bed_bedframewood_ci4[];
extern u8 bouncy_bed_bedframewood_ci4_pal_rgba16[];
extern Vtx bouncy_bed_dl_mesh_layer_1_vtx_0[12];
extern Gfx bouncy_bed_dl_mesh_layer_1_tri_0[];
extern Vtx bouncy_bed_dl_mesh_layer_1_vtx_1[104];
extern Gfx bouncy_bed_dl_mesh_layer_1_tri_1[];
extern Gfx mat_bouncy_bed_WhiteSheets_001[];
extern Gfx mat_revert_bouncy_bed_WhiteSheets_001[];
extern Gfx mat_bouncy_bed_Bedframe_001[];
extern Gfx mat_revert_bouncy_bed_Bedframe_001[];
extern Gfx bouncy_bed_dl_mesh_layer_1[];
extern Gfx bouncy_bed_material_revert_render_settings[];
