extern const GeoLayout dirt_pile_geo[];
extern u8 dirt_pile_multigrass_rgba16_i8[];
extern u8 dirt_pile_multigrass_i4_i4[];
extern Vtx dirt_pile_Dirt_pile_001_mesh_layer_1_vtx_cull[8];
extern Vtx dirt_pile_Dirt_pile_001_mesh_layer_1_vtx_0[13];
extern Gfx dirt_pile_Dirt_pile_001_mesh_layer_1_tri_0[];
extern Gfx mat_dirt_pile_GrassAndDirt_layer1[];
extern Gfx mat_revert_dirt_pile_GrassAndDirt_layer1[];
extern Gfx dirt_pile_Dirt_pile_001_mesh_layer_1[];
extern Gfx dirt_pile_material_revert_render_settings[];
